// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Shippo.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Shippo.OpenApiClient.Carrier_accounts.Register.New
{
    /// <summary>
    /// Builds and executes requests for operations under \carrier_accounts\register\new
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NewRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Shippo.OpenApiClient.Carrier_accounts.Register.New.NewRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NewRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/carrier_accounts/register/new", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Shippo.OpenApiClient.Carrier_accounts.Register.New.NewRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NewRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/carrier_accounts/register/new", rawUrl)
        {
        }
        /// <summary>
        /// Adds a Shippo carrier account
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccount"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Shippo.OpenApiClient.Models.BadRequest">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccount?> PostAsync(global::Soenneker.Shippo.OpenApiClient.Carrier_accounts.Register.New.NewRequestBuilder.NewPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccount> PostAsync(global::Soenneker.Shippo.OpenApiClient.Carrier_accounts.Register.New.NewRequestBuilder.NewPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Shippo.OpenApiClient.Models.BadRequest.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccount>(requestInfo, global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccount.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Adds a Shippo carrier account
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Shippo.OpenApiClient.Carrier_accounts.Register.New.NewRequestBuilder.NewPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Shippo.OpenApiClient.Carrier_accounts.Register.New.NewRequestBuilder.NewPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Carrier_accounts.Register.New.NewRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Shippo.OpenApiClient.Carrier_accounts.Register.New.NewRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Shippo.OpenApiClient.Carrier_accounts.Register.New.NewRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountCanadaPostCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountChronopostCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountColissimoCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountCorreosCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDeutschePostCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDHLExpressCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDpdDeCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDPDUKCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountFedExCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountHermesUKCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountMondialRelayCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountPosteItalianeCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountRoyalMailCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountRoyalMailSfCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountUPSCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountUSPSCreateRequest"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class NewPostRequestBody : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountCanadaPostCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountCanadaPostCreateRequest? CarrierAccountCanadaPostCreateRequest { get; set; }
#nullable restore
#else
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountCanadaPostCreateRequest CarrierAccountCanadaPostCreateRequest { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountChronopostCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountChronopostCreateRequest? CarrierAccountChronopostCreateRequest { get; set; }
#nullable restore
#else
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountChronopostCreateRequest CarrierAccountChronopostCreateRequest { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountColissimoCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountColissimoCreateRequest? CarrierAccountColissimoCreateRequest { get; set; }
#nullable restore
#else
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountColissimoCreateRequest CarrierAccountColissimoCreateRequest { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountCorreosCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountCorreosCreateRequest? CarrierAccountCorreosCreateRequest { get; set; }
#nullable restore
#else
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountCorreosCreateRequest CarrierAccountCorreosCreateRequest { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDeutschePostCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDeutschePostCreateRequest? CarrierAccountDeutschePostCreateRequest { get; set; }
#nullable restore
#else
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDeutschePostCreateRequest CarrierAccountDeutschePostCreateRequest { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDHLExpressCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDHLExpressCreateRequest? CarrierAccountDHLExpressCreateRequest { get; set; }
#nullable restore
#else
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDHLExpressCreateRequest CarrierAccountDHLExpressCreateRequest { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDpdDeCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDpdDeCreateRequest? CarrierAccountDpdDeCreateRequest { get; set; }
#nullable restore
#else
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDpdDeCreateRequest CarrierAccountDpdDeCreateRequest { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDPDUKCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDPDUKCreateRequest? CarrierAccountDPDUKCreateRequest { get; set; }
#nullable restore
#else
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDPDUKCreateRequest CarrierAccountDPDUKCreateRequest { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountFedExCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountFedExCreateRequest? CarrierAccountFedExCreateRequest { get; set; }
#nullable restore
#else
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountFedExCreateRequest CarrierAccountFedExCreateRequest { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountHermesUKCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountHermesUKCreateRequest? CarrierAccountHermesUKCreateRequest { get; set; }
#nullable restore
#else
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountHermesUKCreateRequest CarrierAccountHermesUKCreateRequest { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountMondialRelayCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountMondialRelayCreateRequest? CarrierAccountMondialRelayCreateRequest { get; set; }
#nullable restore
#else
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountMondialRelayCreateRequest CarrierAccountMondialRelayCreateRequest { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountPosteItalianeCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountPosteItalianeCreateRequest? CarrierAccountPosteItalianeCreateRequest { get; set; }
#nullable restore
#else
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountPosteItalianeCreateRequest CarrierAccountPosteItalianeCreateRequest { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountRoyalMailCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountRoyalMailCreateRequest? CarrierAccountRoyalMailCreateRequest { get; set; }
#nullable restore
#else
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountRoyalMailCreateRequest CarrierAccountRoyalMailCreateRequest { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountRoyalMailSfCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountRoyalMailSfCreateRequest? CarrierAccountRoyalMailSfCreateRequest { get; set; }
#nullable restore
#else
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountRoyalMailSfCreateRequest CarrierAccountRoyalMailSfCreateRequest { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountUPSCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountUPSCreateRequest? CarrierAccountUPSCreateRequest { get; set; }
#nullable restore
#else
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountUPSCreateRequest CarrierAccountUPSCreateRequest { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountUSPSCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountUSPSCreateRequest? CarrierAccountUSPSCreateRequest { get; set; }
#nullable restore
#else
            public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountUSPSCreateRequest CarrierAccountUSPSCreateRequest { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Carrier_accounts.Register.New.NewRequestBuilder.NewPostRequestBody"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Shippo.OpenApiClient.Carrier_accounts.Register.New.NewRequestBuilder.NewPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("carrier")?.GetStringValue();
                var result = new global::Soenneker.Shippo.OpenApiClient.Carrier_accounts.Register.New.NewRequestBuilder.NewPostRequestBody();
                if("canada_post".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CarrierAccountCanadaPostCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountCanadaPostCreateRequest();
                }
                else if("chronopost".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CarrierAccountChronopostCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountChronopostCreateRequest();
                }
                else if("colissimo".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CarrierAccountColissimoCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountColissimoCreateRequest();
                }
                else if("correos".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CarrierAccountCorreosCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountCorreosCreateRequest();
                }
                else if("dhl_express".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CarrierAccountDHLExpressCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDHLExpressCreateRequest();
                }
                else if("dpd_uk".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CarrierAccountDPDUKCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDPDUKCreateRequest();
                }
                else if("deutsche_post".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CarrierAccountDeutschePostCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDeutschePostCreateRequest();
                }
                else if("dpd_de".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CarrierAccountDpdDeCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDpdDeCreateRequest();
                }
                else if("fedex".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CarrierAccountFedExCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountFedExCreateRequest();
                }
                else if("hermes_uk".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CarrierAccountHermesUKCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountHermesUKCreateRequest();
                }
                else if("mondial_relay".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CarrierAccountMondialRelayCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountMondialRelayCreateRequest();
                }
                else if("poste_italiane".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CarrierAccountPosteItalianeCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountPosteItalianeCreateRequest();
                }
                else if("royal_mail".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CarrierAccountRoyalMailCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountRoyalMailCreateRequest();
                }
                else if("royal_mail_sf".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CarrierAccountRoyalMailSfCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountRoyalMailSfCreateRequest();
                }
                else if("ups".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CarrierAccountUPSCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountUPSCreateRequest();
                }
                else if("usps".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CarrierAccountUSPSCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountUSPSCreateRequest();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CarrierAccountCanadaPostCreateRequest != null)
                {
                    return CarrierAccountCanadaPostCreateRequest.GetFieldDeserializers();
                }
                else if(CarrierAccountChronopostCreateRequest != null)
                {
                    return CarrierAccountChronopostCreateRequest.GetFieldDeserializers();
                }
                else if(CarrierAccountColissimoCreateRequest != null)
                {
                    return CarrierAccountColissimoCreateRequest.GetFieldDeserializers();
                }
                else if(CarrierAccountCorreosCreateRequest != null)
                {
                    return CarrierAccountCorreosCreateRequest.GetFieldDeserializers();
                }
                else if(CarrierAccountDeutschePostCreateRequest != null)
                {
                    return CarrierAccountDeutschePostCreateRequest.GetFieldDeserializers();
                }
                else if(CarrierAccountDHLExpressCreateRequest != null)
                {
                    return CarrierAccountDHLExpressCreateRequest.GetFieldDeserializers();
                }
                else if(CarrierAccountDpdDeCreateRequest != null)
                {
                    return CarrierAccountDpdDeCreateRequest.GetFieldDeserializers();
                }
                else if(CarrierAccountDPDUKCreateRequest != null)
                {
                    return CarrierAccountDPDUKCreateRequest.GetFieldDeserializers();
                }
                else if(CarrierAccountFedExCreateRequest != null)
                {
                    return CarrierAccountFedExCreateRequest.GetFieldDeserializers();
                }
                else if(CarrierAccountHermesUKCreateRequest != null)
                {
                    return CarrierAccountHermesUKCreateRequest.GetFieldDeserializers();
                }
                else if(CarrierAccountMondialRelayCreateRequest != null)
                {
                    return CarrierAccountMondialRelayCreateRequest.GetFieldDeserializers();
                }
                else if(CarrierAccountPosteItalianeCreateRequest != null)
                {
                    return CarrierAccountPosteItalianeCreateRequest.GetFieldDeserializers();
                }
                else if(CarrierAccountRoyalMailCreateRequest != null)
                {
                    return CarrierAccountRoyalMailCreateRequest.GetFieldDeserializers();
                }
                else if(CarrierAccountRoyalMailSfCreateRequest != null)
                {
                    return CarrierAccountRoyalMailSfCreateRequest.GetFieldDeserializers();
                }
                else if(CarrierAccountUPSCreateRequest != null)
                {
                    return CarrierAccountUPSCreateRequest.GetFieldDeserializers();
                }
                else if(CarrierAccountUSPSCreateRequest != null)
                {
                    return CarrierAccountUSPSCreateRequest.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CarrierAccountCanadaPostCreateRequest != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountCanadaPostCreateRequest>(null, CarrierAccountCanadaPostCreateRequest);
                }
                else if(CarrierAccountChronopostCreateRequest != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountChronopostCreateRequest>(null, CarrierAccountChronopostCreateRequest);
                }
                else if(CarrierAccountColissimoCreateRequest != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountColissimoCreateRequest>(null, CarrierAccountColissimoCreateRequest);
                }
                else if(CarrierAccountCorreosCreateRequest != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountCorreosCreateRequest>(null, CarrierAccountCorreosCreateRequest);
                }
                else if(CarrierAccountDeutschePostCreateRequest != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDeutschePostCreateRequest>(null, CarrierAccountDeutschePostCreateRequest);
                }
                else if(CarrierAccountDHLExpressCreateRequest != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDHLExpressCreateRequest>(null, CarrierAccountDHLExpressCreateRequest);
                }
                else if(CarrierAccountDpdDeCreateRequest != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDpdDeCreateRequest>(null, CarrierAccountDpdDeCreateRequest);
                }
                else if(CarrierAccountDPDUKCreateRequest != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDPDUKCreateRequest>(null, CarrierAccountDPDUKCreateRequest);
                }
                else if(CarrierAccountFedExCreateRequest != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountFedExCreateRequest>(null, CarrierAccountFedExCreateRequest);
                }
                else if(CarrierAccountHermesUKCreateRequest != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountHermesUKCreateRequest>(null, CarrierAccountHermesUKCreateRequest);
                }
                else if(CarrierAccountMondialRelayCreateRequest != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountMondialRelayCreateRequest>(null, CarrierAccountMondialRelayCreateRequest);
                }
                else if(CarrierAccountPosteItalianeCreateRequest != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountPosteItalianeCreateRequest>(null, CarrierAccountPosteItalianeCreateRequest);
                }
                else if(CarrierAccountRoyalMailCreateRequest != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountRoyalMailCreateRequest>(null, CarrierAccountRoyalMailCreateRequest);
                }
                else if(CarrierAccountRoyalMailSfCreateRequest != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountRoyalMailSfCreateRequest>(null, CarrierAccountRoyalMailSfCreateRequest);
                }
                else if(CarrierAccountUPSCreateRequest != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountUPSCreateRequest>(null, CarrierAccountUPSCreateRequest);
                }
                else if(CarrierAccountUSPSCreateRequest != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountUSPSCreateRequest>(null, CarrierAccountUSPSCreateRequest);
                }
            }
        }
    }
}
#pragma warning restore CS0618
