// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Shippo.OpenApiClient.Rates.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Shippo.OpenApiClient.Rates
{
    /// <summary>
    /// Builds and executes requests for operations under \rates
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RatesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Shippo.OpenApiClient.rates.item collection</summary>
        /// <param name="position">Object ID of the rate</param>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Rates.Item.WithRateItemRequestBuilder"/></returns>
        public global::Soenneker.Shippo.OpenApiClient.Rates.Item.WithRateItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("RateId", position);
                return new global::Soenneker.Shippo.OpenApiClient.Rates.Item.WithRateItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Shippo.OpenApiClient.Rates.RatesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RatesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rates", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Shippo.OpenApiClient.Rates.RatesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RatesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rates", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
