// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    /// <summary>Mandatory for Fedex only. License type of the recipient of the Alcohol Package.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Alcohol_recipient_type
    {
        [EnumMember(Value = "licensee")]
        #pragma warning disable CS1591
        Licensee,
        #pragma warning restore CS1591
        [EnumMember(Value = "consumer")]
        #pragma warning disable CS1591
        Consumer,
        #pragma warning restore CS1591
    }
}
