// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    /// <summary>&quot;- `VALIDATING`: the batch is being created and validated- `VALID`: the batch can be purchased- `INVALID`: the batch cannot be purchased; `INVALID` BatchShipments must be removed- `PURCHASING`: the batch is being purchased- `PURCHASED`: the batch is finished purchasing&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BatchStatus
    {
        [EnumMember(Value = "VALIDATING")]
        #pragma warning disable CS1591
        Validating,
        #pragma warning restore CS1591
        [EnumMember(Value = "VALID")]
        #pragma warning disable CS1591
        Valid,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID")]
        #pragma warning disable CS1591
        Invalid,
        #pragma warning restore CS1591
        [EnumMember(Value = "PURCHASING")]
        #pragma warning disable CS1591
        Purchasing,
        #pragma warning restore CS1591
        [EnumMember(Value = "PURCHASED")]
        #pragma warning disable CS1591
        Purchased,
        #pragma warning restore CS1591
    }
}
