// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    /// <summary>Party to be billed. (Leave blank for DHL Germany.)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Billing_type
    {
        [EnumMember(Value = "SENDER")]
        #pragma warning disable CS1591
        SENDER,
        #pragma warning restore CS1591
        [EnumMember(Value = "RECIPIENT")]
        #pragma warning disable CS1591
        RECIPIENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "THIRD_PARTY")]
        #pragma warning disable CS1591
        THIRD_PARTY,
        #pragma warning restore CS1591
        [EnumMember(Value = "THIRD_PARTY_CONSIGNEE")]
        #pragma warning disable CS1591
        THIRD_PARTY_CONSIGNEE,
        #pragma warning restore CS1591
        [EnumMember(Value = "COLLECT")]
        #pragma warning disable CS1591
        COLLECT,
        #pragma warning restore CS1591
    }
}
