// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CarrierAccountCorreosCreateRequest_carrier
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "correos")]
        #pragma warning disable CS1591
        Correos,
        #pragma warning restore CS1591
    }
}
