// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    /// <summary>Policy to indicate if the Account needs multi-factor verification.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CarrierAccountWithExtraInfo_object_info_verification_policy
    {
        [EnumMember(Value = "required")]
        #pragma warning disable CS1591
        Required,
        #pragma warning restore CS1591
        [EnumMember(Value = "not-required")]
        #pragma warning disable CS1591
        NotRequired,
        #pragma warning restore CS1591
    }
}
