// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    /// <summary>|Token | Carrier name||:---|:---|| airterra | Airterra || apc_postal | APC Postal|| apg | APG|| aramex | Aramex|| asendia_us | Asendia US|| australia_post | Australia Post (also used for Startrack)|| axlehire | Jitsu|| better_trucks | BetterTrucks|| borderguru | BorderGuru|| boxberry | Boxberry|| bring | Bring (also used for Posten Norge)|| canada_post | Canada Post|| chronopost | Chronopost|| collect_plus | CollectPlus|| correios_br | CorreiosBR|| correos_espana | Correos España || colissimo | Colissimo|| deutsche_post | Deutsche Post|| dhl_benelux | DHL Benelux|| dhl_ecommerce | DHL eCommerce|| dhl_express | DHL Express|| dhl_germany_c2c | DHL Germany C2C|| dhl_germany | DHL Germany|| dpd_de | DPD GERMANY|| dpd_uk | DPD UK|| estafeta | Estafeta|| fastway_australia | Aramex|| fedex | FedEx|| globegistics | Globegistics (now Asendia)|| gls_us | GLS US|| gophr | Gophr|| gso | GSO|| hermes_germany_b2c | Hermes Germany B2C|| hermes_uk | Evri UK || hongkong_post | Hongkong Post|| lasership | LaserShip|| lso | LSO|| mondial_relay | Mondial Relay|| new_zealand_post | New Zealand Post (also used for Pace and CourierPost)|| nippon_express | Nippon Express|| ontrac | OnTrac|| parcelforce | Parcelforce|| passport | Passport|| pcf | PCF|| poste_italiane | Poste Italiane || posti | Posti|| purolator | Purolator|| royal_mail | Royal Mail|| royal_mail_sf | Royal Mail Storefeeder|| rr_donnelley | ePost Global|| russian_post | Russian Post|| skypostal | SkyPostal|| stuart | Stuart|| swyft | Swyft|| uds | UDS (United Delivery Service)|| ups | UPS|| usps | USPS|| veho | Veho |</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CarriersEnum
    {
        [EnumMember(Value = "airterra")]
        #pragma warning disable CS1591
        Airterra,
        #pragma warning restore CS1591
        [EnumMember(Value = "apc_postal")]
        #pragma warning disable CS1591
        ApcPostal,
        #pragma warning restore CS1591
        [EnumMember(Value = "apg")]
        #pragma warning disable CS1591
        Apg,
        #pragma warning restore CS1591
        [EnumMember(Value = "aramex")]
        #pragma warning disable CS1591
        Aramex,
        #pragma warning restore CS1591
        [EnumMember(Value = "asendia_us")]
        #pragma warning disable CS1591
        AsendiaUs,
        #pragma warning restore CS1591
        [EnumMember(Value = "australia_post")]
        #pragma warning disable CS1591
        AustraliaPost,
        #pragma warning restore CS1591
        [EnumMember(Value = "axlehire")]
        #pragma warning disable CS1591
        Axlehire,
        #pragma warning restore CS1591
        [EnumMember(Value = "better_trucks")]
        #pragma warning disable CS1591
        BetterTrucks,
        #pragma warning restore CS1591
        [EnumMember(Value = "borderguru")]
        #pragma warning disable CS1591
        Borderguru,
        #pragma warning restore CS1591
        [EnumMember(Value = "boxberry")]
        #pragma warning disable CS1591
        Boxberry,
        #pragma warning restore CS1591
        [EnumMember(Value = "bring")]
        #pragma warning disable CS1591
        Bring,
        #pragma warning restore CS1591
        [EnumMember(Value = "canada_post")]
        #pragma warning disable CS1591
        CanadaPost,
        #pragma warning restore CS1591
        [EnumMember(Value = "chronopost")]
        #pragma warning disable CS1591
        Chronopost,
        #pragma warning restore CS1591
        [EnumMember(Value = "collect_plus")]
        #pragma warning disable CS1591
        CollectPlus,
        #pragma warning restore CS1591
        [EnumMember(Value = "correios_br")]
        #pragma warning disable CS1591
        CorreiosBr,
        #pragma warning restore CS1591
        [EnumMember(Value = "correos_espana")]
        #pragma warning disable CS1591
        CorreosEspana,
        #pragma warning restore CS1591
        [EnumMember(Value = "colissimo")]
        #pragma warning disable CS1591
        Colissimo,
        #pragma warning restore CS1591
        [EnumMember(Value = "deutsche_post")]
        #pragma warning disable CS1591
        DeutschePost,
        #pragma warning restore CS1591
        [EnumMember(Value = "dhl_benelux")]
        #pragma warning disable CS1591
        DhlBenelux,
        #pragma warning restore CS1591
        [EnumMember(Value = "dhl_ecommerce")]
        #pragma warning disable CS1591
        DhlEcommerce,
        #pragma warning restore CS1591
        [EnumMember(Value = "dhl_express")]
        #pragma warning disable CS1591
        DhlExpress,
        #pragma warning restore CS1591
        [EnumMember(Value = "dhl_germany_c2c")]
        #pragma warning disable CS1591
        DhlGermanyC2C,
        #pragma warning restore CS1591
        [EnumMember(Value = "dhl_germany")]
        #pragma warning disable CS1591
        DhlGermany,
        #pragma warning restore CS1591
        [EnumMember(Value = "dpd_de")]
        #pragma warning disable CS1591
        DpdDe,
        #pragma warning restore CS1591
        [EnumMember(Value = "dpd_uk")]
        #pragma warning disable CS1591
        DpdUk,
        #pragma warning restore CS1591
        [EnumMember(Value = "estafeta")]
        #pragma warning disable CS1591
        Estafeta,
        #pragma warning restore CS1591
        [EnumMember(Value = "fastway_australia")]
        #pragma warning disable CS1591
        FastwayAustralia,
        #pragma warning restore CS1591
        [EnumMember(Value = "fedex")]
        #pragma warning disable CS1591
        Fedex,
        #pragma warning restore CS1591
        [EnumMember(Value = "globegistics")]
        #pragma warning disable CS1591
        Globegistics,
        #pragma warning restore CS1591
        [EnumMember(Value = "gls_us")]
        #pragma warning disable CS1591
        GlsUs,
        #pragma warning restore CS1591
        [EnumMember(Value = "gophr")]
        #pragma warning disable CS1591
        Gophr,
        #pragma warning restore CS1591
        [EnumMember(Value = "gso")]
        #pragma warning disable CS1591
        Gso,
        #pragma warning restore CS1591
        [EnumMember(Value = "hermes_germany_b2c")]
        #pragma warning disable CS1591
        HermesGermanyB2C,
        #pragma warning restore CS1591
        [EnumMember(Value = "hermes_uk")]
        #pragma warning disable CS1591
        HermesUk,
        #pragma warning restore CS1591
        [EnumMember(Value = "hongkong_post")]
        #pragma warning disable CS1591
        HongkongPost,
        #pragma warning restore CS1591
        [EnumMember(Value = "lasership")]
        #pragma warning disable CS1591
        Lasership,
        #pragma warning restore CS1591
        [EnumMember(Value = "lso")]
        #pragma warning disable CS1591
        Lso,
        #pragma warning restore CS1591
        [EnumMember(Value = "mondial_relay")]
        #pragma warning disable CS1591
        MondialRelay,
        #pragma warning restore CS1591
        [EnumMember(Value = "new_zealand_post")]
        #pragma warning disable CS1591
        NewZealandPost,
        #pragma warning restore CS1591
        [EnumMember(Value = "nippon_express")]
        #pragma warning disable CS1591
        NipponExpress,
        #pragma warning restore CS1591
        [EnumMember(Value = "ontrac")]
        #pragma warning disable CS1591
        Ontrac,
        #pragma warning restore CS1591
        [EnumMember(Value = "parcelforce")]
        #pragma warning disable CS1591
        Parcelforce,
        #pragma warning restore CS1591
        [EnumMember(Value = "passport")]
        #pragma warning disable CS1591
        Passport,
        #pragma warning restore CS1591
        [EnumMember(Value = "pcf")]
        #pragma warning disable CS1591
        Pcf,
        #pragma warning restore CS1591
        [EnumMember(Value = "poste_italiane")]
        #pragma warning disable CS1591
        PosteItaliane,
        #pragma warning restore CS1591
        [EnumMember(Value = "posti")]
        #pragma warning disable CS1591
        Posti,
        #pragma warning restore CS1591
        [EnumMember(Value = "purolator")]
        #pragma warning disable CS1591
        Purolator,
        #pragma warning restore CS1591
        [EnumMember(Value = "royal_mail")]
        #pragma warning disable CS1591
        RoyalMail,
        #pragma warning restore CS1591
        [EnumMember(Value = "royal_mail_sf")]
        #pragma warning disable CS1591
        RoyalMailSf,
        #pragma warning restore CS1591
        [EnumMember(Value = "rr_donnelley")]
        #pragma warning disable CS1591
        RrDonnelley,
        #pragma warning restore CS1591
        [EnumMember(Value = "russian_post")]
        #pragma warning disable CS1591
        RussianPost,
        #pragma warning restore CS1591
        [EnumMember(Value = "skypostal")]
        #pragma warning disable CS1591
        Skypostal,
        #pragma warning restore CS1591
        [EnumMember(Value = "stuart")]
        #pragma warning disable CS1591
        Stuart,
        #pragma warning restore CS1591
        [EnumMember(Value = "swyft")]
        #pragma warning disable CS1591
        Swyft,
        #pragma warning restore CS1591
        [EnumMember(Value = "uds")]
        #pragma warning disable CS1591
        Uds,
        #pragma warning restore CS1591
        [EnumMember(Value = "ups")]
        #pragma warning disable CS1591
        Ups,
        #pragma warning restore CS1591
        [EnumMember(Value = "usps")]
        #pragma warning disable CS1591
        Usps,
        #pragma warning restore CS1591
        [EnumMember(Value = "veho")]
        #pragma warning disable CS1591
        Veho,
        #pragma warning restore CS1591
    }
}
