// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ConnectExistingOwnAccountRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The account_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountId { get; set; }
#nullable restore
#else
        public string AccountId { get; set; }
#endif
        /// <summary>The active property</summary>
        public bool? Active { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The carrier property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Carrier { get; set; }
#nullable restore
#else
        public string Carrier { get; set; }
#endif
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Metadata { get; set; }
#nullable restore
#else
        public string Metadata { get; set; }
#endif
        /// <summary>The parameters property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.ConnectExistingOwnAccountRequest.ConnectExistingOwnAccountRequest_parameters? Parameters { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.ConnectExistingOwnAccountRequest.ConnectExistingOwnAccountRequest_parameters Parameters { get; set; }
#endif
        /// <summary>The test property</summary>
        public bool? Test { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Shippo.OpenApiClient.Models.ConnectExistingOwnAccountRequest"/> and sets the default values.
        /// </summary>
        public ConnectExistingOwnAccountRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.ConnectExistingOwnAccountRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Shippo.OpenApiClient.Models.ConnectExistingOwnAccountRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Shippo.OpenApiClient.Models.ConnectExistingOwnAccountRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_id", n => { AccountId = n.GetStringValue(); } },
                { "active", n => { Active = n.GetBoolValue(); } },
                { "carrier", n => { Carrier = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetStringValue(); } },
                { "parameters", n => { Parameters = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.ConnectExistingOwnAccountRequest.ConnectExistingOwnAccountRequest_parameters>(global::Soenneker.Shippo.OpenApiClient.Models.ConnectExistingOwnAccountRequest.ConnectExistingOwnAccountRequest_parameters.CreateFromDiscriminatorValue); } },
                { "test", n => { Test = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("account_id", AccountId);
            writer.WriteBoolValue("active", Active);
            writer.WriteStringValue("carrier", Carrier);
            writer.WriteStringValue("metadata", Metadata);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.ConnectExistingOwnAccountRequest.ConnectExistingOwnAccountRequest_parameters>("parameters", Parameters);
            writer.WriteBoolValue("test", Test);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Shippo.OpenApiClient.Models.ConnectExistingOwnAccountParameters"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.FedExConnectExistingOwnAccountParameters"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.UPSConnectExistingOwnAccountParameters"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ConnectExistingOwnAccountRequest_parameters : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.ConnectExistingOwnAccountParameters"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Shippo.OpenApiClient.Models.ConnectExistingOwnAccountParameters? ConnectExistingOwnAccountParameters { get; set; }
#nullable restore
#else
            public global::Soenneker.Shippo.OpenApiClient.Models.ConnectExistingOwnAccountParameters ConnectExistingOwnAccountParameters { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.FedExConnectExistingOwnAccountParameters"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Shippo.OpenApiClient.Models.FedExConnectExistingOwnAccountParameters? FedExConnectExistingOwnAccountParameters { get; set; }
#nullable restore
#else
            public global::Soenneker.Shippo.OpenApiClient.Models.FedExConnectExistingOwnAccountParameters FedExConnectExistingOwnAccountParameters { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.UPSConnectExistingOwnAccountParameters"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Shippo.OpenApiClient.Models.UPSConnectExistingOwnAccountParameters? UPSConnectExistingOwnAccountParameters { get; set; }
#nullable restore
#else
            public global::Soenneker.Shippo.OpenApiClient.Models.UPSConnectExistingOwnAccountParameters UPSConnectExistingOwnAccountParameters { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.ConnectExistingOwnAccountRequest.ConnectExistingOwnAccountRequest_parameters"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Shippo.OpenApiClient.Models.ConnectExistingOwnAccountRequest.ConnectExistingOwnAccountRequest_parameters CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Shippo.OpenApiClient.Models.ConnectExistingOwnAccountRequest.ConnectExistingOwnAccountRequest_parameters();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ConnectExistingOwnAccountParameters = new global::Soenneker.Shippo.OpenApiClient.Models.ConnectExistingOwnAccountParameters();
                }
                else if("FedExConnectExistingOwnAccountParameters".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.FedExConnectExistingOwnAccountParameters = new global::Soenneker.Shippo.OpenApiClient.Models.FedExConnectExistingOwnAccountParameters();
                }
                else if("UPSConnectExistingOwnAccountParameters".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.UPSConnectExistingOwnAccountParameters = new global::Soenneker.Shippo.OpenApiClient.Models.UPSConnectExistingOwnAccountParameters();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ConnectExistingOwnAccountParameters != null)
                {
                    return ConnectExistingOwnAccountParameters.GetFieldDeserializers();
                }
                else if(FedExConnectExistingOwnAccountParameters != null)
                {
                    return FedExConnectExistingOwnAccountParameters.GetFieldDeserializers();
                }
                else if(UPSConnectExistingOwnAccountParameters != null)
                {
                    return UPSConnectExistingOwnAccountParameters.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ConnectExistingOwnAccountParameters != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.ConnectExistingOwnAccountParameters>(null, ConnectExistingOwnAccountParameters);
                }
                else if(FedExConnectExistingOwnAccountParameters != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.FedExConnectExistingOwnAccountParameters>(null, FedExConnectExistingOwnAccountParameters);
                }
                else if(UPSConnectExistingOwnAccountParameters != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSConnectExistingOwnAccountParameters>(null, UPSConnectExistingOwnAccountParameters);
                }
            }
        }
    }
}
#pragma warning restore CS0618
