// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CustomsDeclarationEelPfcEnum_value
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "NOEEI_30_37_a")]
        #pragma warning disable CS1591
        NOEEI_30_37_a,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOEEI_30_37_h")]
        #pragma warning disable CS1591
        NOEEI_30_37_h,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOEEI_30_37_f")]
        #pragma warning disable CS1591
        NOEEI_30_37_f,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOEEI_30_36")]
        #pragma warning disable CS1591
        NOEEI_30_36,
        #pragma warning restore CS1591
        [EnumMember(Value = "AES_ITN")]
        #pragma warning disable CS1591
        AES_ITN,
        #pragma warning restore CS1591
    }
}
