// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CustomsDeclarationCreateRequest : global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationBase, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Object that represents the address of the importer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.AddressImporter? AddressImporter { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.AddressImporter AddressImporter { get; set; }
#endif
        /// <summary>The contents_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContentsType { get; set; }
#nullable restore
#else
        public string ContentsType { get; set; }
#endif
        /// <summary>The eel_pfc property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EelPfc { get; set; }
#nullable restore
#else
        public string EelPfc { get; set; }
#endif
        /// <summary>The incoterm property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Incoterm { get; set; }
#nullable restore
#else
        public string Incoterm { get; set; }
#endif
        /// <summary>The items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Shippo.OpenApiClient.Models.CustomsItemCreateRequest>? Items { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Shippo.OpenApiClient.Models.CustomsItemCreateRequest> Items { get; set; }
#endif
        /// <summary>The non_delivery_option property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NonDeliveryOption { get; set; }
#nullable restore
#else
        public string NonDeliveryOption { get; set; }
#endif
        /// <summary>The test property</summary>
        public bool? Test { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationCreateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationCreateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationCreateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "address_importer", n => { AddressImporter = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.AddressImporter>(global::Soenneker.Shippo.OpenApiClient.Models.AddressImporter.CreateFromDiscriminatorValue); } },
                { "contents_type", n => { ContentsType = n.GetStringValue(); } },
                { "eel_pfc", n => { EelPfc = n.GetStringValue(); } },
                { "incoterm", n => { Incoterm = n.GetStringValue(); } },
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::Soenneker.Shippo.OpenApiClient.Models.CustomsItemCreateRequest>(global::Soenneker.Shippo.OpenApiClient.Models.CustomsItemCreateRequest.CreateFromDiscriminatorValue)?.AsList(); } },
                { "non_delivery_option", n => { NonDeliveryOption = n.GetStringValue(); } },
                { "test", n => { Test = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.AddressImporter>("address_importer", AddressImporter);
            writer.WriteStringValue("contents_type", ContentsType);
            writer.WriteStringValue("eel_pfc", EelPfc);
            writer.WriteStringValue("incoterm", Incoterm);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Shippo.OpenApiClient.Models.CustomsItemCreateRequest>("items", Items);
            writer.WriteStringValue("non_delivery_option", NonDeliveryOption);
            writer.WriteBoolValue("test", Test);
        }
    }
}
#pragma warning restore CS0618
