// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CustomsDeclaration : global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationBase, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Object ID of the Importer address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressImporter { get; set; }
#nullable restore
#else
        public string AddressImporter { get; set; }
#endif
        /// <summary>Type of goods of the shipment.  Allowed values available &lt;a href=&quot;/shippoapi/public-api/customs-declaration-contents-type&quot;&gt;here&lt;/a&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContentsType { get; set; }
#nullable restore
#else
        public string ContentsType { get; set; }
#endif
        /// <summary>EEL / PFC type of the shipment. For most shipments from the US to CA, `NOEEI_30_36` is applicable; for most other shipments from the US, `NOEEI_30_37_a` is applicable.Allowed values available &lt;a href=&quot;/shippoapi/public-api/customs-declaration-eelpfc&quot;&gt;here&lt;/a&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EelPfc { get; set; }
#nullable restore
#else
        public string EelPfc { get; set; }
#endif
        /// <summary>The incoterm reference of the shipment. FCA is available for DHL Express and FedEx only.eDAP is available for DPD UK only. DAP is available for DHL Express, FedEx, and DPD UK.If expecting DAP for other carriers, please use DDU.Allowed values available &lt;a href=&quot;/shippoapi/public-api/customs-declaration-incoterm&quot;&gt;here&lt;/a&gt;Carrier-specific restrictions are in the table below.**Carrier-Specific Constraints:**| Carrier | Constraints ||:---|:---|| FedEx | Must be one of DDP, DDU, FCA, DAP |</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Incoterm { get; set; }
#nullable restore
#else
        public string Incoterm { get; set; }
#endif
        /// <summary>Additional invoiced charges to be shown on the Customs Declaration Commercial Invoice.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CustomsInvoicedCharges? InvoicedCharges { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CustomsInvoicedCharges InvoicedCharges { get; set; }
#endif
        /// <summary>Distinct Parcel content items as Customs Items object_ids.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Items { get; set; }
#nullable restore
#else
        public List<string> Items { get; set; }
#endif
        /// <summary>Indicates how the carrier should proceed in case the shipment can&apos;t be delivered.Allowed values available &lt;a href=&quot;/shippoapi/public-api/customs-declaration-non-delivery-option&quot;&gt;here&lt;/a&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NonDeliveryOption { get; set; }
#nullable restore
#else
        public string NonDeliveryOption { get; set; }
#endif
        /// <summary>Date and time of object creation.</summary>
        public DateTimeOffset? ObjectCreated { get; set; }
        /// <summary>Unique identifier of the given object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObjectId { get; set; }
#nullable restore
#else
        public string ObjectId { get; set; }
#endif
        /// <summary>Username of the user who created the object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObjectOwner { get; set; }
#nullable restore
#else
        public string ObjectOwner { get; set; }
#endif
        /// <summary>Indicates the validity of the enclosing object</summary>
        public global::Soenneker.Shippo.OpenApiClient.Models.ObjectStateEnum? ObjectState { get; set; }
        /// <summary>Date and time of last object update.</summary>
        public DateTimeOffset? ObjectUpdated { get; set; }
        /// <summary>Indicates whether the object has been created in test mode.</summary>
        public bool? Test { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclaration"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclaration CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclaration();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "address_importer", n => { AddressImporter = n.GetStringValue(); } },
                { "contents_type", n => { ContentsType = n.GetStringValue(); } },
                { "eel_pfc", n => { EelPfc = n.GetStringValue(); } },
                { "incoterm", n => { Incoterm = n.GetStringValue(); } },
                { "invoiced_charges", n => { InvoicedCharges = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CustomsInvoicedCharges>(global::Soenneker.Shippo.OpenApiClient.Models.CustomsInvoicedCharges.CreateFromDiscriminatorValue); } },
                { "items", n => { Items = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "non_delivery_option", n => { NonDeliveryOption = n.GetStringValue(); } },
                { "object_created", n => { ObjectCreated = n.GetDateTimeOffsetValue(); } },
                { "object_id", n => { ObjectId = n.GetStringValue(); } },
                { "object_owner", n => { ObjectOwner = n.GetStringValue(); } },
                { "object_state", n => { ObjectState = n.GetEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.ObjectStateEnum>(); } },
                { "object_updated", n => { ObjectUpdated = n.GetDateTimeOffsetValue(); } },
                { "test", n => { Test = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteStringValue("address_importer", AddressImporter);
            writer.WriteStringValue("contents_type", ContentsType);
            writer.WriteStringValue("eel_pfc", EelPfc);
            writer.WriteStringValue("incoterm", Incoterm);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CustomsInvoicedCharges>("invoiced_charges", InvoicedCharges);
            writer.WriteCollectionOfPrimitiveValues<string>("items", Items);
            writer.WriteStringValue("non_delivery_option", NonDeliveryOption);
            writer.WriteDateTimeOffsetValue("object_created", ObjectCreated);
            writer.WriteStringValue("object_id", ObjectId);
            writer.WriteStringValue("object_owner", ObjectOwner);
            writer.WriteEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.ObjectStateEnum>("object_state", ObjectState);
            writer.WriteDateTimeOffsetValue("object_updated", ObjectUpdated);
            writer.WriteBoolValue("test", Test);
        }
    }
}
#pragma warning restore CS0618
