// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    /// <summary>
    /// Specifies who will pay the duties for the shipment. Only accepted for FedEx shipments.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CustomsDeclarationBase_duties_payor : IAdditionalDataHolder, IParsable
    {
        /// <summary>Account number to be billed for duties.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Account { get; set; }
#nullable restore
#else
        public string Account { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationBase_duties_payor_address? Address { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationBase_duties_payor_address Address { get; set; }
#endif
        /// <summary>Party to be billed for duties.</summary>
        public global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationBase_duties_payor_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationBase_duties_payor"/> and sets the default values.
        /// </summary>
        public CustomsDeclarationBase_duties_payor()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationBase_duties_payor"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationBase_duties_payor CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationBase_duties_payor();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account", n => { Account = n.GetStringValue(); } },
                { "address", n => { Address = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationBase_duties_payor_address>(global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationBase_duties_payor_address.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationBase_duties_payor_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("account", Account);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationBase_duties_payor_address>("address", Address);
            writer.WriteEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationBase_duties_payor_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
