// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CustomsDeclarationCreateRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Object that represents the address of the importer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.AddressImporter? AddressImporter { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.AddressImporter AddressImporter { get; set; }
#endif
        /// <summary>**required if eel_pfc is `AES_ITN`**&lt;br&gt;AES / ITN reference of the shipment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AesItn { get; set; }
#nullable restore
#else
        public string AesItn { get; set; }
#endif
        /// <summary>The b13a_filing_option property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? B13aFilingOption { get; set; }
#nullable restore
#else
        public string B13aFilingOption { get; set; }
#endif
        /// <summary>**must be provided if and only if b13a_filing_option is provided**&lt;br&gt;Represents:&lt;br&gt; the Proof of Report (POR) Number when b13a_filing_option is `FILED_ELECTRONICALLY`;&lt;br&gt; the Summary ID Number when b13a_filing_option is `SUMMARY_REPORTING`;&lt;br&gt; or the Exemption Number when b13a_filing_option is `NOT_REQUIRED`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? B13aNumber { get; set; }
#nullable restore
#else
        public string B13aNumber { get; set; }
#endif
        /// <summary>Certificate reference of the shipment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Certificate { get; set; }
#nullable restore
#else
        public string Certificate { get; set; }
#endif
        /// <summary>Expresses that the certify_signer has provided all information of this customs declaration truthfully.</summary>
        public bool? Certify { get; set; }
        /// <summary>Name of the person who created the customs declaration and is responsible for the validity of all information provided.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CertifySigner { get; set; }
#nullable restore
#else
        public string CertifySigner { get; set; }
#endif
        /// <summary>The commercial_invoice property</summary>
        public bool? CommercialInvoice { get; set; }
        /// <summary>**required if contents_type is `OTHER`**&lt;br&gt;Explanation of the type of goods of the shipment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContentsExplanation { get; set; }
#nullable restore
#else
        public string ContentsExplanation { get; set; }
#endif
        /// <summary>The contents_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationContentsTypeEnum? ContentsType { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationContentsTypeEnum ContentsType { get; set; }
#endif
        /// <summary>Disclaimer for the shipment and customs information that have been provided.**Carrier-Specific Constraints:**| Carrier | Constraints ||:---|:---|| FedEx | Max 554 characters |</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Disclaimer { get; set; }
#nullable restore
#else
        public string Disclaimer { get; set; }
#endif
        /// <summary>Specifies who will pay the duties for the shipment. Only accepted for FedEx shipments.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationBaseDutiesPayor? DutiesPayor { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationBaseDutiesPayor DutiesPayor { get; set; }
#endif
        /// <summary>The eel_pfc property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationEelPfcEnum? EelPfc { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationEelPfcEnum EelPfc { get; set; }
#endif
        /// <summary>Additional exporter identification that may be required to ship in certain countries</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CustomsExporterIdentification? ExporterIdentification { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CustomsExporterIdentification ExporterIdentification { get; set; }
#endif
        /// <summary>Exporter reference of an export shipment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExporterReference { get; set; }
#nullable restore
#else
        public string ExporterReference { get; set; }
#endif
        /// <summary>Importer reference of an import shipment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImporterReference { get; set; }
#nullable restore
#else
        public string ImporterReference { get; set; }
#endif
        /// <summary>The incoterm property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationIncotermEnum? Incoterm { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationIncotermEnum Incoterm { get; set; }
#endif
        /// <summary>Invoice reference of the shipment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Invoice { get; set; }
#nullable restore
#else
        public string Invoice { get; set; }
#endif
        /// <summary>Indicates whether the shipment&apos;s destination VAT has been collected. May be required for some destinations.</summary>
        public bool? IsVatCollected { get; set; }
        /// <summary>The items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Shippo.OpenApiClient.Models.CustomsItemCreateRequest>? Items { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Shippo.OpenApiClient.Models.CustomsItemCreateRequest> Items { get; set; }
#endif
        /// <summary>License reference of the shipment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? License { get; set; }
#nullable restore
#else
        public string License { get; set; }
#endif
        /// <summary>A string of up to 100 characters that can be filled with any additional information you want to attach to the object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Metadata { get; set; }
#nullable restore
#else
        public string Metadata { get; set; }
#endif
        /// <summary>The non_delivery_option property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationNonDeliveryOptionEnum? NonDeliveryOption { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationNonDeliveryOptionEnum NonDeliveryOption { get; set; }
#endif
        /// <summary>Additional notes to be included in the customs declaration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Notes { get; set; }
#nullable restore
#else
        public string Notes { get; set; }
#endif
        /// <summary>The test property</summary>
        public bool? Test { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationCreateRequest"/> and sets the default values.
        /// </summary>
        public CustomsDeclarationCreateRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationCreateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationCreateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationCreateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address_importer", n => { AddressImporter = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.AddressImporter>(global::Soenneker.Shippo.OpenApiClient.Models.AddressImporter.CreateFromDiscriminatorValue); } },
                { "aes_itn", n => { AesItn = n.GetStringValue(); } },
                { "b13a_filing_option", n => { B13aFilingOption = n.GetStringValue(); } },
                { "b13a_number", n => { B13aNumber = n.GetStringValue(); } },
                { "certificate", n => { Certificate = n.GetStringValue(); } },
                { "certify", n => { Certify = n.GetBoolValue(); } },
                { "certify_signer", n => { CertifySigner = n.GetStringValue(); } },
                { "commercial_invoice", n => { CommercialInvoice = n.GetBoolValue(); } },
                { "contents_explanation", n => { ContentsExplanation = n.GetStringValue(); } },
                { "contents_type", n => { ContentsType = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationContentsTypeEnum>(global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationContentsTypeEnum.CreateFromDiscriminatorValue); } },
                { "disclaimer", n => { Disclaimer = n.GetStringValue(); } },
                { "duties_payor", n => { DutiesPayor = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationBaseDutiesPayor>(global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationBaseDutiesPayor.CreateFromDiscriminatorValue); } },
                { "eel_pfc", n => { EelPfc = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationEelPfcEnum>(global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationEelPfcEnum.CreateFromDiscriminatorValue); } },
                { "exporter_identification", n => { ExporterIdentification = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CustomsExporterIdentification>(global::Soenneker.Shippo.OpenApiClient.Models.CustomsExporterIdentification.CreateFromDiscriminatorValue); } },
                { "exporter_reference", n => { ExporterReference = n.GetStringValue(); } },
                { "importer_reference", n => { ImporterReference = n.GetStringValue(); } },
                { "incoterm", n => { Incoterm = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationIncotermEnum>(global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationIncotermEnum.CreateFromDiscriminatorValue); } },
                { "invoice", n => { Invoice = n.GetStringValue(); } },
                { "is_vat_collected", n => { IsVatCollected = n.GetBoolValue(); } },
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::Soenneker.Shippo.OpenApiClient.Models.CustomsItemCreateRequest>(global::Soenneker.Shippo.OpenApiClient.Models.CustomsItemCreateRequest.CreateFromDiscriminatorValue)?.AsList(); } },
                { "license", n => { License = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetStringValue(); } },
                { "non_delivery_option", n => { NonDeliveryOption = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationNonDeliveryOptionEnum>(global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationNonDeliveryOptionEnum.CreateFromDiscriminatorValue); } },
                { "notes", n => { Notes = n.GetStringValue(); } },
                { "test", n => { Test = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.AddressImporter>("address_importer", AddressImporter);
            writer.WriteStringValue("aes_itn", AesItn);
            writer.WriteStringValue("b13a_filing_option", B13aFilingOption);
            writer.WriteStringValue("b13a_number", B13aNumber);
            writer.WriteStringValue("certificate", Certificate);
            writer.WriteBoolValue("certify", Certify);
            writer.WriteStringValue("certify_signer", CertifySigner);
            writer.WriteBoolValue("commercial_invoice", CommercialInvoice);
            writer.WriteStringValue("contents_explanation", ContentsExplanation);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationContentsTypeEnum>("contents_type", ContentsType);
            writer.WriteStringValue("disclaimer", Disclaimer);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationBaseDutiesPayor>("duties_payor", DutiesPayor);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationEelPfcEnum>("eel_pfc", EelPfc);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CustomsExporterIdentification>("exporter_identification", ExporterIdentification);
            writer.WriteStringValue("exporter_reference", ExporterReference);
            writer.WriteStringValue("importer_reference", ImporterReference);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationIncotermEnum>("incoterm", Incoterm);
            writer.WriteStringValue("invoice", Invoice);
            writer.WriteBoolValue("is_vat_collected", IsVatCollected);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Shippo.OpenApiClient.Models.CustomsItemCreateRequest>("items", Items);
            writer.WriteStringValue("license", License);
            writer.WriteStringValue("metadata", Metadata);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationNonDeliveryOptionEnum>("non_delivery_option", NonDeliveryOption);
            writer.WriteStringValue("notes", Notes);
            writer.WriteBoolValue("test", Test);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
