// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CustomsItem : global::Soenneker.Shippo.OpenApiClient.Models.CustomsItemBase, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Date and time of object creation.</summary>
        public DateTimeOffset? ObjectCreated { get; set; }
        /// <summary>Unique identifier of the given object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObjectId { get; set; }
#nullable restore
#else
        public string ObjectId { get; set; }
#endif
        /// <summary>Username of the user who created the object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObjectOwner { get; set; }
#nullable restore
#else
        public string ObjectOwner { get; set; }
#endif
        /// <summary>Indicates the validity of the enclosing object</summary>
        public global::Soenneker.Shippo.OpenApiClient.Models.ObjectStateEnum? ObjectState { get; set; }
        /// <summary>Date and time of last object update.</summary>
        public DateTimeOffset? ObjectUpdated { get; set; }
        /// <summary>Indicates whether the object has been created in test mode.</summary>
        public bool? Test { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CustomsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Shippo.OpenApiClient.Models.CustomsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Shippo.OpenApiClient.Models.CustomsItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "object_created", n => { ObjectCreated = n.GetDateTimeOffsetValue(); } },
                { "object_id", n => { ObjectId = n.GetStringValue(); } },
                { "object_owner", n => { ObjectOwner = n.GetStringValue(); } },
                { "object_state", n => { ObjectState = n.GetEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.ObjectStateEnum>(); } },
                { "object_updated", n => { ObjectUpdated = n.GetDateTimeOffsetValue(); } },
                { "test", n => { Test = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteDateTimeOffsetValue("object_created", ObjectCreated);
            writer.WriteStringValue("object_id", ObjectId);
            writer.WriteStringValue("object_owner", ObjectOwner);
            writer.WriteEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.ObjectStateEnum>("object_state", ObjectState);
            writer.WriteDateTimeOffsetValue("object_updated", ObjectUpdated);
            writer.WriteBoolValue("test", Test);
        }
    }
}
#pragma warning restore CS0618
