// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    /// <summary>
    /// Container for specifying the presence of dangerous materials. This is specific to USPS, and if any contentsare provided, only certain USPS service levels will be eligible. For more information, see our&lt;a href=&quot;https://docs.goshippo.com/docs/shipments/hazmat/&quot;&gt;guide on hazardous or dangerous materials shipping&lt;/a&gt;.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DangerousGoodsObject : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Container for specifying the presence of biological material.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.DangerousGoodsBiologicalMaterial? BiologicalMaterial { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.DangerousGoodsBiologicalMaterial BiologicalMaterial { get; set; }
#endif
        /// <summary>Indicates if the shipment contains dangerous goods.</summary>
        public bool? Contains { get; set; }
        /// <summary>Container for specifying the presence of lithium batteries.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.DangerousGoodsLithiumBatteries? LithiumBatteries { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.DangerousGoodsLithiumBatteries LithiumBatteries { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Shippo.OpenApiClient.Models.DangerousGoodsObject"/> and sets the default values.
        /// </summary>
        public DangerousGoodsObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.DangerousGoodsObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Shippo.OpenApiClient.Models.DangerousGoodsObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Shippo.OpenApiClient.Models.DangerousGoodsObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "biological_material", n => { BiologicalMaterial = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.DangerousGoodsBiologicalMaterial>(global::Soenneker.Shippo.OpenApiClient.Models.DangerousGoodsBiologicalMaterial.CreateFromDiscriminatorValue); } },
                { "contains", n => { Contains = n.GetBoolValue(); } },
                { "lithium_batteries", n => { LithiumBatteries = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.DangerousGoodsLithiumBatteries>(global::Soenneker.Shippo.OpenApiClient.Models.DangerousGoodsLithiumBatteries.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.DangerousGoodsBiologicalMaterial>("biological_material", BiologicalMaterial);
            writer.WriteBoolValue("contains", Contains);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.DangerousGoodsLithiumBatteries>("lithium_batteries", LithiumBatteries);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
