// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetCarrierRegistrationStatusCarrierParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ups")]
        #pragma warning disable CS1591
        Ups,
        #pragma warning restore CS1591
        [EnumMember(Value = "usps")]
        #pragma warning disable CS1591
        Usps,
        #pragma warning restore CS1591
        [EnumMember(Value = "canada_post")]
        #pragma warning disable CS1591
        CanadaPost,
        #pragma warning restore CS1591
    }
}
