// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class InstantTransactionCreateRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The async property</summary>
        public bool? Async { get; set; }
        /// <summary>The carrier_account property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CarrierAccount { get; set; }
#nullable restore
#else
        public string CarrierAccount { get; set; }
#endif
        /// <summary>The label_file_type property</summary>
        public global::Soenneker.Shippo.OpenApiClient.Models.InstantTransactionCreateRequest_label_file_type? LabelFileType { get; set; }
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Metadata { get; set; }
#nullable restore
#else
        public string Metadata { get; set; }
#endif
        /// <summary>The order property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Order { get; set; }
#nullable restore
#else
        public string Order { get; set; }
#endif
        /// <summary>The servicelevel_token property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServicelevelToken { get; set; }
#nullable restore
#else
        public string ServicelevelToken { get; set; }
#endif
        /// <summary>The shipment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequest? Shipment { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequest Shipment { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Shippo.OpenApiClient.Models.InstantTransactionCreateRequest"/> and sets the default values.
        /// </summary>
        public InstantTransactionCreateRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.InstantTransactionCreateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Shippo.OpenApiClient.Models.InstantTransactionCreateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Shippo.OpenApiClient.Models.InstantTransactionCreateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "async", n => { Async = n.GetBoolValue(); } },
                { "carrier_account", n => { CarrierAccount = n.GetStringValue(); } },
                { "label_file_type", n => { LabelFileType = n.GetEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.InstantTransactionCreateRequest_label_file_type>(); } },
                { "metadata", n => { Metadata = n.GetStringValue(); } },
                { "order", n => { Order = n.GetStringValue(); } },
                { "servicelevel_token", n => { ServicelevelToken = n.GetStringValue(); } },
                { "shipment", n => { Shipment = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequest>(global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequest.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("async", Async);
            writer.WriteStringValue("carrier_account", CarrierAccount);
            writer.WriteEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.InstantTransactionCreateRequest_label_file_type>("label_file_type", LabelFileType);
            writer.WriteStringValue("metadata", Metadata);
            writer.WriteStringValue("order", Order);
            writer.WriteStringValue("servicelevel_token", ServicelevelToken);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequest>("shipment", Shipment);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
