// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    /// <summary>To have insurance cover provided by a carrier directly instead of Shippo&apos;s provider (XCover), set `provider` to `FEDEX`, `UPS`, or `ONTRAC`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InsuranceProvider
    {
        [EnumMember(Value = "FEDEX")]
        #pragma warning disable CS1591
        Fedex,
        #pragma warning restore CS1591
        [EnumMember(Value = "UPS")]
        #pragma warning disable CS1591
        Ups,
        #pragma warning restore CS1591
        [EnumMember(Value = "ONTRAC")]
        #pragma warning disable CS1591
        Ontrac,
        #pragma warning restore CS1591
    }
}
