// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LiveRateCreateRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The sender address, which includes your name, company name, street address, city, state, zip code, country, phone number, and email address (strings). Special characters should not be included in any address element, especially name, company, and email.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.LiveRateCreateRequestAddressFrom? AddressFrom { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.LiveRateCreateRequestAddressFrom AddressFrom { get; set; }
#endif
        /// <summary>The recipient address, which includes the recipient&apos;s name, company name, street address, city, state, zip code, country, phone number, and email address (strings). Special characters should not be included in any address element, especially name, company, and email.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.LiveRateCreateRequestAddressTo? AddressTo { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.LiveRateCreateRequestAddressTo AddressTo { get; set; }
#endif
        /// <summary>Array of Line Item objects</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Shippo.OpenApiClient.Models.LineItem>? LineItems { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Shippo.OpenApiClient.Models.LineItem> LineItems { get; set; }
#endif
        /// <summary>Object ID for an existing User Parcel Template OR a fully formed Parcel object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.LiveRateCreateRequestParcel? Parcel { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.LiveRateCreateRequestParcel Parcel { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Shippo.OpenApiClient.Models.LiveRateCreateRequest"/> and sets the default values.
        /// </summary>
        public LiveRateCreateRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.LiveRateCreateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Shippo.OpenApiClient.Models.LiveRateCreateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Shippo.OpenApiClient.Models.LiveRateCreateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address_from", n => { AddressFrom = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.LiveRateCreateRequestAddressFrom>(global::Soenneker.Shippo.OpenApiClient.Models.LiveRateCreateRequestAddressFrom.CreateFromDiscriminatorValue); } },
                { "address_to", n => { AddressTo = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.LiveRateCreateRequestAddressTo>(global::Soenneker.Shippo.OpenApiClient.Models.LiveRateCreateRequestAddressTo.CreateFromDiscriminatorValue); } },
                { "line_items", n => { LineItems = n.GetCollectionOfObjectValues<global::Soenneker.Shippo.OpenApiClient.Models.LineItem>(global::Soenneker.Shippo.OpenApiClient.Models.LineItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "parcel", n => { Parcel = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.LiveRateCreateRequestParcel>(global::Soenneker.Shippo.OpenApiClient.Models.LiveRateCreateRequestParcel.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.LiveRateCreateRequestAddressFrom>("address_from", AddressFrom);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.LiveRateCreateRequestAddressTo>("address_to", AddressTo);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Shippo.OpenApiClient.Models.LineItem>("line_items", LineItems);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.LiveRateCreateRequestParcel>("parcel", Parcel);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
