// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    /// <summary>
    /// Location where the parcel(s) will be picked up.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Location : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The pickup address, which includes your name, company name, street address, city, state, zip code, country, phone number, and email address (strings). Special characters should not be included in any address element, especially name, company, and email.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.AddressPickupCompleteCreateRequest? Address { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.AddressPickupCompleteCreateRequest Address { get; set; }
#endif
        /// <summary>Where your parcels will be available for pickup. &quot;Security Deck&quot; and &quot;Shipping Dock&quot; are only supported for DHL Express.</summary>
        public global::Soenneker.Shippo.OpenApiClient.Models.Location_building_location_type? BuildingLocationType { get; set; }
        /// <summary>The type of building where the pickup is located.</summary>
        public global::Soenneker.Shippo.OpenApiClient.Models.Location_building_type? BuildingType { get; set; }
        /// <summary>Pickup instructions for the courier. This is a mandatory field if the building_location_type is &quot;Other&quot;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Instructions { get; set; }
#nullable restore
#else
        public string Instructions { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Shippo.OpenApiClient.Models.Location"/> and sets the default values.
        /// </summary>
        public Location()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.Location"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Shippo.OpenApiClient.Models.Location CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Shippo.OpenApiClient.Models.Location();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.AddressPickupCompleteCreateRequest>(global::Soenneker.Shippo.OpenApiClient.Models.AddressPickupCompleteCreateRequest.CreateFromDiscriminatorValue); } },
                { "building_location_type", n => { BuildingLocationType = n.GetEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.Location_building_location_type>(); } },
                { "building_type", n => { BuildingType = n.GetEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.Location_building_type>(); } },
                { "instructions", n => { Instructions = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.AddressPickupCompleteCreateRequest>("address", Address);
            writer.WriteEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.Location_building_location_type>("building_location_type", BuildingLocationType);
            writer.WriteEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.Location_building_type>("building_type", BuildingType);
            writer.WriteStringValue("instructions", Instructions);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
