// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    /// <summary>Indicates the status of the manifest.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ManifestStatus
    {
        [EnumMember(Value = "QUEUED")]
        #pragma warning disable CS1591
        Queued,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUCCESS")]
        #pragma warning disable CS1591
        Success,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
    }
}
