// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OrderBase : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>**Required if total_price is provided**&lt;br&gt;Currency of the &lt;code&gt;total_price&lt;/code&gt; and &lt;code&gt;total_tax&lt;/code&gt; amounts.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>Custom buyer- or seller-provided notes about the order.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Notes { get; set; }
#nullable restore
#else
        public string Notes { get; set; }
#endif
        /// <summary>An alphanumeric identifier for the order used by the seller/buyer. This identifier doesn&apos;t need to be unique.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrderNumber { get; set; }
#nullable restore
#else
        public string OrderNumber { get; set; }
#endif
        /// <summary>Current state of the order. See the &lt;a href=&quot;https://docs.goshippo.com/docs/orders/orders/&quot;&gt;orders tutorial&lt;/a&gt; for the logic of how the status is handled.</summary>
        public global::Soenneker.Shippo.OpenApiClient.Models.OrderStatusEnum? OrderStatus { get; set; }
        /// <summary>Date and time when the order was placed. This datetime can be different from the datetime of the order object creation on Shippo.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlacedAt { get; set; }
#nullable restore
#else
        public string PlacedAt { get; set; }
#endif
        /// <summary>Amount paid by the buyer for shipping. This amount can be different from the price the seller will actually pay for shipping.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShippingCost { get; set; }
#nullable restore
#else
        public string ShippingCost { get; set; }
#endif
        /// <summary>**Required if shipping_cost is provided**&lt;br&gt;Currency of the &lt;code&gt;shipping_cost&lt;/code&gt; amount.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShippingCostCurrency { get; set; }
#nullable restore
#else
        public string ShippingCostCurrency { get; set; }
#endif
        /// <summary>Shipping method (carrier + service or other free text description) chosen by the buyer. This value can be different from the shipping method the seller will actually choose.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShippingMethod { get; set; }
#nullable restore
#else
        public string ShippingMethod { get; set; }
#endif
        /// <summary>The subtotal_price property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubtotalPrice { get; set; }
#nullable restore
#else
        public string SubtotalPrice { get; set; }
#endif
        /// <summary>Total amount paid by the buyer for this order.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotalPrice { get; set; }
#nullable restore
#else
        public string TotalPrice { get; set; }
#endif
        /// <summary>Total tax amount paid by the buyer for this order.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotalTax { get; set; }
#nullable restore
#else
        public string TotalTax { get; set; }
#endif
        /// <summary>Total weight of the order.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Weight { get; set; }
#nullable restore
#else
        public string Weight { get; set; }
#endif
        /// <summary>The unit used for weight.</summary>
        public global::Soenneker.Shippo.OpenApiClient.Models.WeightUnitEnum? WeightUnit { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Shippo.OpenApiClient.Models.OrderBase"/> and sets the default values.
        /// </summary>
        public OrderBase()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.OrderBase"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Shippo.OpenApiClient.Models.OrderBase CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Shippo.OpenApiClient.Models.OrderBase();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currency", n => { Currency = n.GetStringValue(); } },
                { "notes", n => { Notes = n.GetStringValue(); } },
                { "order_number", n => { OrderNumber = n.GetStringValue(); } },
                { "order_status", n => { OrderStatus = n.GetEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.OrderStatusEnum>(); } },
                { "placed_at", n => { PlacedAt = n.GetStringValue(); } },
                { "shipping_cost", n => { ShippingCost = n.GetStringValue(); } },
                { "shipping_cost_currency", n => { ShippingCostCurrency = n.GetStringValue(); } },
                { "shipping_method", n => { ShippingMethod = n.GetStringValue(); } },
                { "subtotal_price", n => { SubtotalPrice = n.GetStringValue(); } },
                { "total_price", n => { TotalPrice = n.GetStringValue(); } },
                { "total_tax", n => { TotalTax = n.GetStringValue(); } },
                { "weight", n => { Weight = n.GetStringValue(); } },
                { "weight_unit", n => { WeightUnit = n.GetEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.WeightUnitEnum>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("currency", Currency);
            writer.WriteStringValue("notes", Notes);
            writer.WriteStringValue("order_number", OrderNumber);
            writer.WriteEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.OrderStatusEnum>("order_status", OrderStatus);
            writer.WriteStringValue("placed_at", PlacedAt);
            writer.WriteStringValue("shipping_cost", ShippingCost);
            writer.WriteStringValue("shipping_cost_currency", ShippingCostCurrency);
            writer.WriteStringValue("shipping_method", ShippingMethod);
            writer.WriteStringValue("subtotal_price", SubtotalPrice);
            writer.WriteStringValue("total_price", TotalPrice);
            writer.WriteStringValue("total_tax", TotalTax);
            writer.WriteStringValue("weight", Weight);
            writer.WriteEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.WeightUnitEnum>("weight_unit", WeightUnit);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
