// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    /// <summary>Current state of the order. See the &lt;a href=&quot;https://docs.goshippo.com/docs/orders/orders/&quot;&gt;orders tutorial&lt;/a&gt; for the logic of how the status is handled.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OrderStatusEnum
    {
        [EnumMember(Value = "UNKNOWN")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "AWAITPAY")]
        #pragma warning disable CS1591
        Awaitpay,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAID")]
        #pragma warning disable CS1591
        Paid,
        #pragma warning restore CS1591
        [EnumMember(Value = "REFUNDED")]
        #pragma warning disable CS1591
        Refunded,
        #pragma warning restore CS1591
        [EnumMember(Value = "CANCELLED")]
        #pragma warning disable CS1591
        Cancelled,
        #pragma warning restore CS1591
        [EnumMember(Value = "PARTIALLY_FULFILLED")]
        #pragma warning disable CS1591
        PartiallyFulfilled,
        #pragma warning restore CS1591
        [EnumMember(Value = "SHIPPED")]
        #pragma warning disable CS1591
        Shipped,
        #pragma warning restore CS1591
    }
}
