// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    /// <summary>Platform the order was created on and, if applicable, imported from. Orders created via the Shippo API or dashboard will have the value &quot;Shippo&quot;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OrderShopAppEnum
    {
        [EnumMember(Value = "Amazon")]
        #pragma warning disable CS1591
        Amazon,
        #pragma warning restore CS1591
        [EnumMember(Value = "Bigcommerce")]
        #pragma warning disable CS1591
        Bigcommerce,
        #pragma warning restore CS1591
        [EnumMember(Value = "CSV_Import")]
        #pragma warning disable CS1591
        CSV_Import,
        #pragma warning restore CS1591
        [EnumMember(Value = "eBay")]
        #pragma warning disable CS1591
        EBay,
        #pragma warning restore CS1591
        [EnumMember(Value = "ePages")]
        #pragma warning disable CS1591
        EPages,
        #pragma warning restore CS1591
        [EnumMember(Value = "Etsy")]
        #pragma warning disable CS1591
        Etsy,
        #pragma warning restore CS1591
        [EnumMember(Value = "Godaddy")]
        #pragma warning disable CS1591
        Godaddy,
        #pragma warning restore CS1591
        [EnumMember(Value = "Magento")]
        #pragma warning disable CS1591
        Magento,
        #pragma warning restore CS1591
        [EnumMember(Value = "Shippo")]
        #pragma warning disable CS1591
        Shippo,
        #pragma warning restore CS1591
        [EnumMember(Value = "Shopify")]
        #pragma warning disable CS1591
        Shopify,
        #pragma warning restore CS1591
        [EnumMember(Value = "Spreecommerce")]
        #pragma warning disable CS1591
        Spreecommerce,
        #pragma warning restore CS1591
        [EnumMember(Value = "StripeRelay")]
        #pragma warning disable CS1591
        StripeRelay,
        #pragma warning restore CS1591
        [EnumMember(Value = "Walmart")]
        #pragma warning disable CS1591
        Walmart,
        #pragma warning restore CS1591
        [EnumMember(Value = "Weebly")]
        #pragma warning disable CS1591
        Weebly,
        #pragma warning restore CS1591
        [EnumMember(Value = "WooCommerce")]
        #pragma warning disable CS1591
        WooCommerce,
        #pragma warning restore CS1591
    }
}
