// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    /// <summary>|Token | Name | Dimensions||:---|:---|:---|| DPD_UK_Express_Pak| DPD UK Express Pak | 530.00 x 400.00 x 100.00 mm|</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ParcelTemplateDpdukEnum
    {
        [EnumMember(Value = "DPD_UK_Express_Pak")]
        #pragma warning disable CS1591
        DpdUkExpressPak,
        #pragma warning restore CS1591
    }
}
