// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    /// <summary>|Token | Name | Dimensions||:---|:---|:---|| USPS_FlatRateCardboardEnvelope | Flat Rate Cardboard Envelope |  12.50 x 9.50 x 0.75 in || USPS_FlatRateEnvelope | Flat Rate Envelope |  12.50 x 9.50 x 0.75 in || USPS_FlatRateGiftCardEnvelope | Flat Rate Gift Card Envelope |  10.00 x 7.00 x 0.75 in || USPS_FlatRateLegalEnvelope | Flat Rate Legal Envelope |  15.00 x 9.50 x 0.75 in || USPS_FlatRatePaddedEnvelope | Flat Rate Padded Envelope |  12.50 x 9.50 x 1.00 in || USPS_FlatRateWindowEnvelope | Flat Rate Window Envelope |  10.00 x 5.00 x 0.75 in || USPS_IrregularParcel | Irregular Parcel |  0.00 x 0.00 x 0.00 in || USPS_LargeFlatRateBoardGameBox | Large Flat Rate Board Game Box |  24.06 x 11.88 x 3.13 in || USPS_LargeFlatRateBox | Large Flat Rate Box |  12.25 x 12.25 x 6.00 in || USPS_APOFlatRateBox | APO/FPO/DPO Large Flat Rate Box |  12.25 x 12.25 x 6.00 in || USPS_LargeVideoFlatRateBox | Flat Rate Large Video Box (Int&amp;#39;l only) |  9.60 x 6.40 x 2.20 in || USPS_MediumFlatRateBox1 | Medium Flat Rate Box 1 |  11.25 x 8.75 x 6.00 in || USPS_MediumFlatRateBox2 | Medium Flat Rate Box 2 |  14.00 x 12.00 x 3.50 in || USPS_RegionalRateBoxA1 | Regional Rate Box A1 |  10.13 x 7.13 x 5.00 in || USPS_RegionalRateBoxA2 | Regional Rate Box A2 |  13.06 x 11.06 x 2.50 in || USPS_RegionalRateBoxB1 | Regional Rate Box B1 |  12.25 x 10.50 x 5.50 in || USPS_RegionalRateBoxB2 | Regional Rate Box B2 |  16.25 x 14.50 x 3.00 in || USPS_SmallFlatRateBox | Small Flat Rate Box |  8.69 x 5.44 x 1.75 in || USPS_SmallFlatRateEnvelope | Small Flat Rate Envelope |  10.00 x 6.00 x 4.00 in || USPS_SoftPack | Soft Pack Padded Envelope |  Length and width defined in the Parcel|</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ParcelTemplateUspsEnum
    {
        [EnumMember(Value = "USPS_FlatRateCardboardEnvelope")]
        #pragma warning disable CS1591
        UspsFlatRateCardboardEnvelope,
        #pragma warning restore CS1591
        [EnumMember(Value = "USPS_FlatRateEnvelope")]
        #pragma warning disable CS1591
        UspsFlatRateEnvelope,
        #pragma warning restore CS1591
        [EnumMember(Value = "USPS_FlatRateGiftCardEnvelope")]
        #pragma warning disable CS1591
        UspsFlatRateGiftCardEnvelope,
        #pragma warning restore CS1591
        [EnumMember(Value = "USPS_FlatRateLegalEnvelope")]
        #pragma warning disable CS1591
        UspsFlatRateLegalEnvelope,
        #pragma warning restore CS1591
        [EnumMember(Value = "USPS_FlatRatePaddedEnvelope")]
        #pragma warning disable CS1591
        UspsFlatRatePaddedEnvelope,
        #pragma warning restore CS1591
        [EnumMember(Value = "USPS_FlatRateWindowEnvelope")]
        #pragma warning disable CS1591
        UspsFlatRateWindowEnvelope,
        #pragma warning restore CS1591
        [EnumMember(Value = "USPS_IrregularParcel")]
        #pragma warning disable CS1591
        UspsIrregularParcel,
        #pragma warning restore CS1591
        [EnumMember(Value = "USPS_LargeFlatRateBoardGameBox")]
        #pragma warning disable CS1591
        UspsLargeFlatRateBoardGameBox,
        #pragma warning restore CS1591
        [EnumMember(Value = "USPS_LargeFlatRateBox")]
        #pragma warning disable CS1591
        UspsLargeFlatRateBox,
        #pragma warning restore CS1591
        [EnumMember(Value = "USPS_APOFlatRateBox")]
        #pragma warning disable CS1591
        UspsApoFlatRateBox,
        #pragma warning restore CS1591
        [EnumMember(Value = "USPS_LargeVideoFlatRateBox")]
        #pragma warning disable CS1591
        UspsLargeVideoFlatRateBox,
        #pragma warning restore CS1591
        [EnumMember(Value = "USPS_MediumFlatRateBox1")]
        #pragma warning disable CS1591
        UspsMediumFlatRateBox1,
        #pragma warning restore CS1591
        [EnumMember(Value = "USPS_MediumFlatRateBox2")]
        #pragma warning disable CS1591
        UspsMediumFlatRateBox2,
        #pragma warning restore CS1591
        [EnumMember(Value = "USPS_RegionalRateBoxA1")]
        #pragma warning disable CS1591
        UspsRegionalRateBoxA1,
        #pragma warning restore CS1591
        [EnumMember(Value = "USPS_RegionalRateBoxA2")]
        #pragma warning disable CS1591
        UspsRegionalRateBoxA2,
        #pragma warning restore CS1591
        [EnumMember(Value = "USPS_RegionalRateBoxB1")]
        #pragma warning disable CS1591
        UspsRegionalRateBoxB1,
        #pragma warning restore CS1591
        [EnumMember(Value = "USPS_RegionalRateBoxB2")]
        #pragma warning disable CS1591
        UspsRegionalRateBoxB2,
        #pragma warning restore CS1591
        [EnumMember(Value = "USPS_SmallFlatRateBox")]
        #pragma warning disable CS1591
        UspsSmallFlatRateBox,
        #pragma warning restore CS1591
        [EnumMember(Value = "USPS_SmallFlatRateEnvelope")]
        #pragma warning disable CS1591
        UspsSmallFlatRateEnvelope,
        #pragma warning restore CS1591
        [EnumMember(Value = "USPS_SoftPack")]
        #pragma warning disable CS1591
        UspsSoftPack,
        #pragma warning restore CS1591
    }
}
