// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PickupBase : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The object ID of your USPS or DHL Express carrier account. You can retrieve this from your Rate requests or our &lt;a href=&quot;/shippoapi/public-api/carrier-accounts&quot;&gt;Carrier Accounts&lt;/a&gt; endpoint.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CarrierAccount { get; set; }
#nullable restore
#else
        public string CarrierAccount { get; set; }
#endif
        /// <summary>Location where the parcel(s) will be picked up.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.Location? Location { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.Location Location { get; set; }
#endif
        /// <summary>A string of up to 100 characters that can be filled with any additional information you want to attach to the object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Metadata { get; set; }
#nullable restore
#else
        public string Metadata { get; set; }
#endif
        /// <summary>The latest that you requested your parcels to be available for pickup. Expressed in the timezone specified in the response.</summary>
        public DateTimeOffset? RequestedEndTime { get; set; }
        /// <summary>The earliest that you requested your parcels to be ready for pickup. Expressed in the timezone specified in the response.</summary>
        public DateTimeOffset? RequestedStartTime { get; set; }
        /// <summary>The transaction(s) object ID(s) for the parcel(s) that need to be picked up.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Transactions { get; set; }
#nullable restore
#else
        public List<string> Transactions { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Shippo.OpenApiClient.Models.PickupBase"/> and sets the default values.
        /// </summary>
        public PickupBase()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.PickupBase"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Shippo.OpenApiClient.Models.PickupBase CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Shippo.OpenApiClient.Models.PickupBase();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "carrier_account", n => { CarrierAccount = n.GetStringValue(); } },
                { "location", n => { Location = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.Location>(global::Soenneker.Shippo.OpenApiClient.Models.Location.CreateFromDiscriminatorValue); } },
                { "metadata", n => { Metadata = n.GetStringValue(); } },
                { "requested_end_time", n => { RequestedEndTime = n.GetDateTimeOffsetValue(); } },
                { "requested_start_time", n => { RequestedStartTime = n.GetDateTimeOffsetValue(); } },
                { "transactions", n => { Transactions = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("carrier_account", CarrierAccount);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.Location>("location", Location);
            writer.WriteStringValue("metadata", Metadata);
            writer.WriteDateTimeOffsetValue("requested_end_time", RequestedEndTime);
            writer.WriteDateTimeOffsetValue("requested_start_time", RequestedStartTime);
            writer.WriteCollectionOfPrimitiveValues<string>("transactions", Transactions);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
