// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Rate : global::Soenneker.Shippo.OpenApiClient.Models.RateAmountAndCurrency, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Predicted time the carrier will deliver the package in the destination&apos;s local time zone. In the format `HH:MM:SS`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ArrivesBy { get; set; }
#nullable restore
#else
        public string ArrivesBy { get; set; }
#endif
        /// <summary>An array containing specific attributes of this Rate in context of the entire shipment. Attributes can be assigned `CHEAPEST`, `FASTEST`, or `BESTVALUE`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Shippo.OpenApiClient.Models.Rate_attributes?>? Attributes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Shippo.OpenApiClient.Models.Rate_attributes?> Attributes { get; set; }
#endif
        /// <summary>Object ID of the carrier account that has been used to retrieve the rate.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CarrierAccount { get; set; }
#nullable restore
#else
        public string CarrierAccount { get; set; }
#endif
        /// <summary>Further clarification of the transit times. Often, this includes notes that the transit time as given in &quot;days&quot; is only an average, not a guaranteed time.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DurationTerms { get; set; }
#nullable restore
#else
        public string DurationTerms { get; set; }
#endif
        /// <summary>Estimated transit time (duration) in days of the Parcel at the given servicelevel. Please note that this is not binding, but only an average value as given by the provider. Shippo is not able to guarantee any transit times.</summary>
        public long? EstimatedDays { get; set; }
        /// <summary>Cost to the user to insure the Rate for the requested amount of coverage, if insurance coverage was requested. Expressed in the currency used in the sender&apos;s country. Will be null if no insurance coverage was requested, or if insurance is requested from a non-standard insurance provider. Please note this price is already included in the `amount` and `amount_local` fields on the Rate. Do not add this field to them.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IncludedInsurancePrice { get; set; }
#nullable restore
#else
        public string IncludedInsurancePrice { get; set; }
#endif
        /// <summary>The messages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Shippo.OpenApiClient.Models.ResponseMessage>? Messages { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Shippo.OpenApiClient.Models.ResponseMessage> Messages { get; set; }
#endif
        /// <summary>Date and time of Rate creation.</summary>
        public DateTimeOffset? ObjectCreated { get; set; }
        /// <summary>Unique identifier of the given Rate object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObjectId { get; set; }
#nullable restore
#else
        public string ObjectId { get; set; }
#endif
        /// <summary>Username of the user who created the rate object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObjectOwner { get; set; }
#nullable restore
#else
        public string ObjectOwner { get; set; }
#endif
        /// <summary>Carrier offering the rate, e.g., `FedEx` or `Deutsche Post DHL`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Provider { get; set; }
#nullable restore
#else
        public string Provider { get; set; }
#endif
        /// <summary>URL to the provider logo with max. dimensions of 200*200px. Please refer to the provider&apos;s Logo Usage Guidelines before using the logo.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProviderImage200 { get; set; }
#nullable restore
#else
        public string ProviderImage200 { get; set; }
#endif
        /// <summary>URL to the provider logo with max. dimensions of 75*75px. Please refer to the provider&apos;s Logo Usage Guidelines before using the logo.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProviderImage75 { get; set; }
#nullable restore
#else
        public string ProviderImage75 { get; set; }
#endif
        /// <summary>The servicelevel property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.ServiceLevelWithParent? Servicelevel { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.ServiceLevelWithParent Servicelevel { get; set; }
#endif
        /// <summary>The shipment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Shipment { get; set; }
#nullable restore
#else
        public string Shipment { get; set; }
#endif
        /// <summary>Indicates whether the object has been created in test mode.</summary>
        public bool? Test { get; set; }
        /// <summary>The parcel&apos;s transit zone token. These tokens can vary depending on the provider.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Zone { get; set; }
#nullable restore
#else
        public string Zone { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.Rate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Shippo.OpenApiClient.Models.Rate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Shippo.OpenApiClient.Models.Rate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "arrives_by", n => { ArrivesBy = n.GetStringValue(); } },
                { "attributes", n => { Attributes = n.GetCollectionOfEnumValues<global::Soenneker.Shippo.OpenApiClient.Models.Rate_attributes>()?.AsList(); } },
                { "carrier_account", n => { CarrierAccount = n.GetStringValue(); } },
                { "duration_terms", n => { DurationTerms = n.GetStringValue(); } },
                { "estimated_days", n => { EstimatedDays = n.GetLongValue(); } },
                { "included_insurance_price", n => { IncludedInsurancePrice = n.GetStringValue(); } },
                { "messages", n => { Messages = n.GetCollectionOfObjectValues<global::Soenneker.Shippo.OpenApiClient.Models.ResponseMessage>(global::Soenneker.Shippo.OpenApiClient.Models.ResponseMessage.CreateFromDiscriminatorValue)?.AsList(); } },
                { "object_created", n => { ObjectCreated = n.GetDateTimeOffsetValue(); } },
                { "object_id", n => { ObjectId = n.GetStringValue(); } },
                { "object_owner", n => { ObjectOwner = n.GetStringValue(); } },
                { "provider", n => { Provider = n.GetStringValue(); } },
                { "provider_image_200", n => { ProviderImage200 = n.GetStringValue(); } },
                { "provider_image_75", n => { ProviderImage75 = n.GetStringValue(); } },
                { "servicelevel", n => { Servicelevel = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.ServiceLevelWithParent>(global::Soenneker.Shippo.OpenApiClient.Models.ServiceLevelWithParent.CreateFromDiscriminatorValue); } },
                { "shipment", n => { Shipment = n.GetStringValue(); } },
                { "test", n => { Test = n.GetBoolValue(); } },
                { "zone", n => { Zone = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteStringValue("arrives_by", ArrivesBy);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Shippo.OpenApiClient.Models.Rate_attributes>("attributes", Attributes);
            writer.WriteStringValue("carrier_account", CarrierAccount);
            writer.WriteStringValue("duration_terms", DurationTerms);
            writer.WriteLongValue("estimated_days", EstimatedDays);
            writer.WriteStringValue("included_insurance_price", IncludedInsurancePrice);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Shippo.OpenApiClient.Models.ResponseMessage>("messages", Messages);
            writer.WriteDateTimeOffsetValue("object_created", ObjectCreated);
            writer.WriteStringValue("object_id", ObjectId);
            writer.WriteStringValue("object_owner", ObjectOwner);
            writer.WriteStringValue("provider", Provider);
            writer.WriteStringValue("provider_image_200", ProviderImage200);
            writer.WriteStringValue("provider_image_75", ProviderImage75);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.ServiceLevelWithParent>("servicelevel", Servicelevel);
            writer.WriteStringValue("shipment", Shipment);
            writer.WriteBoolValue("test", Test);
            writer.WriteStringValue("zone", Zone);
        }
    }
}
#pragma warning restore CS0618
