// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    /// <summary>Indicates the status of the Refund.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Refund_status
    {
        [EnumMember(Value = "QUEUED")]
        #pragma warning disable CS1591
        QUEUED,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENDING")]
        #pragma warning disable CS1591
        PENDING,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUCCESS")]
        #pragma warning disable CS1591
        SUCCESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR")]
        #pragma warning disable CS1591
        ERROR,
        #pragma warning restore CS1591
    }
}
