// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountCanadaPostCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountChronopostCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountColissimoCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountCorreosCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDeutschePostCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDHLExpressCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDpdDeCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDPDUKCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountFedExCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountHermesUKCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountMondialRelayCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountPosteItalianeCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountRoyalMailCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountRoyalMailSfCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountUPSCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountUSPSCreateRequest"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RegisterCarrierAccount : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountCanadaPostCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountCanadaPostCreateRequest? CarrierAccountCanadaPostCreateRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountCanadaPostCreateRequest CarrierAccountCanadaPostCreateRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountChronopostCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountChronopostCreateRequest? CarrierAccountChronopostCreateRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountChronopostCreateRequest CarrierAccountChronopostCreateRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountColissimoCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountColissimoCreateRequest? CarrierAccountColissimoCreateRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountColissimoCreateRequest CarrierAccountColissimoCreateRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountCorreosCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountCorreosCreateRequest? CarrierAccountCorreosCreateRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountCorreosCreateRequest CarrierAccountCorreosCreateRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDeutschePostCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDeutschePostCreateRequest? CarrierAccountDeutschePostCreateRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDeutschePostCreateRequest CarrierAccountDeutschePostCreateRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDHLExpressCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDHLExpressCreateRequest? CarrierAccountDHLExpressCreateRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDHLExpressCreateRequest CarrierAccountDHLExpressCreateRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDpdDeCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDpdDeCreateRequest? CarrierAccountDpdDeCreateRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDpdDeCreateRequest CarrierAccountDpdDeCreateRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDPDUKCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDPDUKCreateRequest? CarrierAccountDPDUKCreateRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDPDUKCreateRequest CarrierAccountDPDUKCreateRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountFedExCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountFedExCreateRequest? CarrierAccountFedExCreateRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountFedExCreateRequest CarrierAccountFedExCreateRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountHermesUKCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountHermesUKCreateRequest? CarrierAccountHermesUKCreateRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountHermesUKCreateRequest CarrierAccountHermesUKCreateRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountMondialRelayCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountMondialRelayCreateRequest? CarrierAccountMondialRelayCreateRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountMondialRelayCreateRequest CarrierAccountMondialRelayCreateRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountPosteItalianeCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountPosteItalianeCreateRequest? CarrierAccountPosteItalianeCreateRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountPosteItalianeCreateRequest CarrierAccountPosteItalianeCreateRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountRoyalMailCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountRoyalMailCreateRequest? CarrierAccountRoyalMailCreateRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountRoyalMailCreateRequest CarrierAccountRoyalMailCreateRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountRoyalMailSfCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountRoyalMailSfCreateRequest? CarrierAccountRoyalMailSfCreateRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountRoyalMailSfCreateRequest CarrierAccountRoyalMailSfCreateRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountUPSCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountUPSCreateRequest? CarrierAccountUPSCreateRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountUPSCreateRequest CarrierAccountUPSCreateRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountUSPSCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountUSPSCreateRequest? CarrierAccountUSPSCreateRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountUSPSCreateRequest CarrierAccountUSPSCreateRequest { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.RegisterCarrierAccount"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Shippo.OpenApiClient.Models.RegisterCarrierAccount CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("carrier")?.GetStringValue();
            var result = new global::Soenneker.Shippo.OpenApiClient.Models.RegisterCarrierAccount();
            if("canada_post".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CarrierAccountCanadaPostCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountCanadaPostCreateRequest();
            }
            else if("CarrierAccountChronopostCreateRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CarrierAccountChronopostCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountChronopostCreateRequest();
            }
            else if("CarrierAccountColissimoCreateRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CarrierAccountColissimoCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountColissimoCreateRequest();
            }
            else if("CarrierAccountCorreosCreateRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CarrierAccountCorreosCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountCorreosCreateRequest();
            }
            else if("CarrierAccountDHLExpressCreateRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CarrierAccountDHLExpressCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDHLExpressCreateRequest();
            }
            else if("CarrierAccountDPDUKCreateRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CarrierAccountDPDUKCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDPDUKCreateRequest();
            }
            else if("CarrierAccountDeutschePostCreateRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CarrierAccountDeutschePostCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDeutschePostCreateRequest();
            }
            else if("CarrierAccountDpdDeCreateRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CarrierAccountDpdDeCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDpdDeCreateRequest();
            }
            else if("CarrierAccountFedExCreateRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CarrierAccountFedExCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountFedExCreateRequest();
            }
            else if("CarrierAccountHermesUKCreateRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CarrierAccountHermesUKCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountHermesUKCreateRequest();
            }
            else if("CarrierAccountMondialRelayCreateRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CarrierAccountMondialRelayCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountMondialRelayCreateRequest();
            }
            else if("CarrierAccountPosteItalianeCreateRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CarrierAccountPosteItalianeCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountPosteItalianeCreateRequest();
            }
            else if("CarrierAccountRoyalMailCreateRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CarrierAccountRoyalMailCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountRoyalMailCreateRequest();
            }
            else if("CarrierAccountRoyalMailSfCreateRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CarrierAccountRoyalMailSfCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountRoyalMailSfCreateRequest();
            }
            else if("CarrierAccountUPSCreateRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CarrierAccountUPSCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountUPSCreateRequest();
            }
            else if("CarrierAccountUSPSCreateRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CarrierAccountUSPSCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountUSPSCreateRequest();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CarrierAccountCanadaPostCreateRequest != null)
            {
                return CarrierAccountCanadaPostCreateRequest.GetFieldDeserializers();
            }
            else if(CarrierAccountChronopostCreateRequest != null)
            {
                return CarrierAccountChronopostCreateRequest.GetFieldDeserializers();
            }
            else if(CarrierAccountColissimoCreateRequest != null)
            {
                return CarrierAccountColissimoCreateRequest.GetFieldDeserializers();
            }
            else if(CarrierAccountCorreosCreateRequest != null)
            {
                return CarrierAccountCorreosCreateRequest.GetFieldDeserializers();
            }
            else if(CarrierAccountDeutschePostCreateRequest != null)
            {
                return CarrierAccountDeutschePostCreateRequest.GetFieldDeserializers();
            }
            else if(CarrierAccountDHLExpressCreateRequest != null)
            {
                return CarrierAccountDHLExpressCreateRequest.GetFieldDeserializers();
            }
            else if(CarrierAccountDpdDeCreateRequest != null)
            {
                return CarrierAccountDpdDeCreateRequest.GetFieldDeserializers();
            }
            else if(CarrierAccountDPDUKCreateRequest != null)
            {
                return CarrierAccountDPDUKCreateRequest.GetFieldDeserializers();
            }
            else if(CarrierAccountFedExCreateRequest != null)
            {
                return CarrierAccountFedExCreateRequest.GetFieldDeserializers();
            }
            else if(CarrierAccountHermesUKCreateRequest != null)
            {
                return CarrierAccountHermesUKCreateRequest.GetFieldDeserializers();
            }
            else if(CarrierAccountMondialRelayCreateRequest != null)
            {
                return CarrierAccountMondialRelayCreateRequest.GetFieldDeserializers();
            }
            else if(CarrierAccountPosteItalianeCreateRequest != null)
            {
                return CarrierAccountPosteItalianeCreateRequest.GetFieldDeserializers();
            }
            else if(CarrierAccountRoyalMailCreateRequest != null)
            {
                return CarrierAccountRoyalMailCreateRequest.GetFieldDeserializers();
            }
            else if(CarrierAccountRoyalMailSfCreateRequest != null)
            {
                return CarrierAccountRoyalMailSfCreateRequest.GetFieldDeserializers();
            }
            else if(CarrierAccountUPSCreateRequest != null)
            {
                return CarrierAccountUPSCreateRequest.GetFieldDeserializers();
            }
            else if(CarrierAccountUSPSCreateRequest != null)
            {
                return CarrierAccountUSPSCreateRequest.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(CarrierAccountCanadaPostCreateRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountCanadaPostCreateRequest>(null, CarrierAccountCanadaPostCreateRequest);
            }
            else if(CarrierAccountChronopostCreateRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountChronopostCreateRequest>(null, CarrierAccountChronopostCreateRequest);
            }
            else if(CarrierAccountColissimoCreateRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountColissimoCreateRequest>(null, CarrierAccountColissimoCreateRequest);
            }
            else if(CarrierAccountCorreosCreateRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountCorreosCreateRequest>(null, CarrierAccountCorreosCreateRequest);
            }
            else if(CarrierAccountDeutschePostCreateRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDeutschePostCreateRequest>(null, CarrierAccountDeutschePostCreateRequest);
            }
            else if(CarrierAccountDHLExpressCreateRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDHLExpressCreateRequest>(null, CarrierAccountDHLExpressCreateRequest);
            }
            else if(CarrierAccountDpdDeCreateRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDpdDeCreateRequest>(null, CarrierAccountDpdDeCreateRequest);
            }
            else if(CarrierAccountDPDUKCreateRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountDPDUKCreateRequest>(null, CarrierAccountDPDUKCreateRequest);
            }
            else if(CarrierAccountFedExCreateRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountFedExCreateRequest>(null, CarrierAccountFedExCreateRequest);
            }
            else if(CarrierAccountHermesUKCreateRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountHermesUKCreateRequest>(null, CarrierAccountHermesUKCreateRequest);
            }
            else if(CarrierAccountMondialRelayCreateRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountMondialRelayCreateRequest>(null, CarrierAccountMondialRelayCreateRequest);
            }
            else if(CarrierAccountPosteItalianeCreateRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountPosteItalianeCreateRequest>(null, CarrierAccountPosteItalianeCreateRequest);
            }
            else if(CarrierAccountRoyalMailCreateRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountRoyalMailCreateRequest>(null, CarrierAccountRoyalMailCreateRequest);
            }
            else if(CarrierAccountRoyalMailSfCreateRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountRoyalMailSfCreateRequest>(null, CarrierAccountRoyalMailSfCreateRequest);
            }
            else if(CarrierAccountUPSCreateRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountUPSCreateRequest>(null, CarrierAccountUPSCreateRequest);
            }
            else if(CarrierAccountUSPSCreateRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CarrierAccountUSPSCreateRequest>(null, CarrierAccountUSPSCreateRequest);
            }
        }
    }
}
#pragma warning restore CS0618
