// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    /// <summary>
    /// An object holding optional extra services to be requested.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ShipmentExtra : IAdditionalDataHolder, IParsable
    {
        /// <summary>UPS only. Adds custom accounts receivable customer account reference to UPS labels.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields? AccountsReceivableCustomerAccount { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields AccountsReceivableCustomerAccount { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Indicates that a shipment contains Alcohol (Fedex and UPS only).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.Alcohol? Alcohol { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.Alcohol Alcohol { get; set; }
#endif
        /// <summary>Specify an ancillary service endorsement to provide the USPS with instructions on how to handle undeliverable-as-addressed pieces (DHL eCommerce only).</summary>
        public global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra_ancillary_endorsement? AncillaryEndorsement { get; set; }
        /// <summary>UPS only. Adds custom appropriation number reference to UPS labels.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields? AppropriationNumber { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields AppropriationNumber { get; set; }
#endif
        /// <summary>Request `true` to give carrier permission to leave the parcel in a safe place if no one answers the door (where supported). When set to `false`, if no one is available to receive the item, the parcel will not be left (*surcharges may be applicable).</summary>
        public bool? AuthorityToLeave { get; set; }
        /// <summary>Specify billing details (UPS, FedEx, and DHL Germany only).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.Billing? Billing { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.Billing Billing { get; set; }
#endif
        /// <summary>UPS only. Adds custom bill of lading number reference to UPS labels.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields? BillOfLadingNumber { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields BillOfLadingNumber { get; set; }
#endif
        /// <summary>Bypasses address validation (USPS, UPS, &amp; LaserShip only).</summary>
        public bool? BypassAddressValidation { get; set; }
        /// <summary>Request carbon offsets by passing true (UPS only).</summary>
        public bool? CarbonNeutral { get; set; }
        /// <summary>Identifies the carrier injection site.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CarrierHubId { get; set; }
#nullable restore
#else
        public string CarrierHubId { get; set; }
#endif
        /// <summary>Travel time in hours from fulfillment center to carrier injection site.</summary>
        public int? CarrierHubTravelTime { get; set; }
        /// <summary>Specify collection on delivery details (UPS only).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.COD? COD { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.COD COD { get; set; }
#endif
        /// <summary>UPS only. Adds custom COD number reference to UPS labels.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields? CodNumber { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields CodNumber { get; set; }
#endif
        /// <summary>Specify container type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContainerType { get; set; }
#nullable restore
#else
        public string ContainerType { get; set; }
#endif
        /// <summary>Carrier arrival time to pickup packages from the fulfillment center. UTC format: `%Y-%m-%dT%H:%M:%SZ`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CriticalPullTime { get; set; }
#nullable restore
#else
        public string CriticalPullTime { get; set; }
#endif
        /// <summary>Specify customer branch (Lasership only).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerBranch { get; set; }
#nullable restore
#else
        public string CustomerBranch { get; set; }
#endif
        /// <summary>Specify the reference field on the label (FedEx and UPS only).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CustomerReference? CustomerReference { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CustomerReference CustomerReference { get; set; }
#endif
        /// <summary>Container for specifying the presence of dangerous materials. This is specific to USPS, and if any contentsare provided, only certain USPS service levels will be eligible. For more information, see our&lt;a href=&quot;https://docs.goshippo.com/docs/shipments/hazmat/&quot;&gt;guide on hazardous or dangerous materials shipping&lt;/a&gt;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.DangerousGoodsObject? DangerousGoods { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.DangerousGoodsObject DangerousGoods { get; set; }
#endif
        /// <summary>Dangerous Goods Code (DHL eCommerce only). See &lt;a href=&quot;https://api-legacy.dhlecs.com/docs/v2/appendix.html#dangerous-goods&quot;&gt;Category Codes&lt;/a&gt;</summary>
        public global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra_dangerous_goods_code? DangerousGoodsCode { get; set; }
        /// <summary>UPS only. Adds custom dealer order number reference to UPS labels.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields? DealerOrderNumber { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields DealerOrderNumber { get; set; }
#endif
        /// <summary>Specify delivery instructions. Up to 500 characters. (FedEx and OnTrac only).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeliveryInstructions { get; set; }
#nullable restore
#else
        public string DeliveryInstructions { get; set; }
#endif
        /// <summary>Specify the department number field on the label (FedEx and UPS only).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.DepartmentNumber? DeptNumber { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.DepartmentNumber DeptNumber { get; set; }
#endif
        /// <summary>Specify that the package contains Dry Ice (FedEx, Veho, and UPS only).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.DryIce? DryIce { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.DryIce DryIce { get; set; }
#endif
        /// <summary>UPS only. Adds custom FDA product code reference to UPS labels.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields? FdaProductCode { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields FdaProductCode { get; set; }
#endif
        /// <summary>The fulfilment center where the package originates from.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FulfillmentCenter { get; set; }
#nullable restore
#else
        public string FulfillmentCenter { get; set; }
#endif
        /// <summary>To add 3rd party insurance powered by &lt;a href=&quot;https://docs.goshippo.com/docs/shipments/shippinginsurance/&quot;&gt;XCover&lt;/a&gt;, specify &lt;br&gt; `amount`, `content`, and `currency`. &lt;br&gt; Alternatively, you can choose carrier provided insurance by additionally specifying `provider` (UPS, FedEx and OnTrac only). &lt;br&gt;&lt;br&gt; If you do not want to add insurance to your shipment, do not set these parameters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.Insurance? Insurance { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.Insurance Insurance { get; set; }
#endif
        /// <summary>Specify the invoice number field on the label (FedEx and UPS only).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.InvoiceNumber? InvoiceNumber { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.InvoiceNumber InvoiceNumber { get; set; }
#endif
        /// <summary>This field specifies if it is a scan-based return shipment. See the &lt;a href=&quot;https://docs.goshippo.com/docs/shipments/returns/&quot;&gt;Create a return shipment&lt;/a&gt; section for more details.</summary>
        public bool? IsReturn { get; set; }
        /// <summary>Specify Lasership Attributes (Lasership only). Multiple options accepted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtraLasershipAttributesEnum?>? LasershipAttrs { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtraLasershipAttributesEnum?> LasershipAttrs { get; set; }
#endif
        /// <summary>Declared value (Lasership only). Defaults to `50.00`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LasershipDeclaredValue { get; set; }
#nullable restore
#else
        public string LasershipDeclaredValue { get; set; }
#endif
        /// <summary>UPS only. Adds custom manifest number reference to UPS labels.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields? ManifestNumber { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields ManifestNumber { get; set; }
#endif
        /// <summary>UPS only. Adds custom model number reference to UPS labels.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields? ModelNumber { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields ModelNumber { get; set; }
#endif
        /// <summary>UPS only. Adds custom part number reference to UPS labels.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields? PartNumber { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields PartNumber { get; set; }
#endif
        /// <summary>Specify the PO number field on the label (FedEx and UPS only).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.PoNumber? PoNumber { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.PoNumber PoNumber { get; set; }
#endif
        /// <summary>Required for DHL Germany Paket Sameday. Designates a desired timeframe for delivery. Format is `HHMMHHMM`</summary>
        public global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra_preferred_delivery_timeframe? PreferredDeliveryTimeframe { get; set; }
        /// <summary>Add premium service to a shipment (DHL Germany international shipments only).</summary>
        public bool? Premium { get; set; }
        /// <summary>UPS only. Adds custom product code reference to UPS labels.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields? ProductionCode { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields ProductionCode { get; set; }
#endif
        /// <summary>UPS only. Adds custom purchase request number reference to UPS labels.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields? PurchaseRequestNumber { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields PurchaseRequestNumber { get; set; }
#endif
        /// <summary>Request a QR code for a given transaction when creating a shipping label (USPS domestic and Evri UK only).</summary>
        public bool? QrCodeRequested { get; set; }
        /// <summary>Optional text to be printed on the shipping label if supported by carrier. Up to 50 characters.**Carrier-Specific Constraints:**| Carrier | Constraints ||:---|:---|| FedEx | Max 40 characters (Express services); Max 30 characters (Ground services) |</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reference1 { get; set; }
#nullable restore
#else
        public string Reference1 { get; set; }
#endif
        /// <summary>Optional text to be printed on the shipping label if supported by carrier. Up to 50 characters. For DHL eCommerce, this field can be used for billing reference.**Carrier-Specific Constraints:**| Carrier | Constraints ||:---|:---|| FedEx | Max 30 characters |</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reference2 { get; set; }
#nullable restore
#else
        public string Reference2 { get; set; }
#endif
        /// <summary>Returns retail rates instead of account-based rates (UPS and FedEx only).</summary>
        public bool? RequestRetailRates { get; set; }
        /// <summary>Request additional return option for return shipments (UPS and Lasership only).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra.ShipmentExtra_return_service_type? ReturnServiceType { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra.ShipmentExtra_return_service_type ReturnServiceType { get; set; }
#endif
        /// <summary>Specify the RMA number field on the label (FedEx and UPS only).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.RmaNumber? RmaNumber { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.RmaNumber RmaNumber { get; set; }
#endif
        /// <summary>UPS only. Adds custom salesperson number reference to UPS labels.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields? SalespersonNumber { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields SalespersonNumber { get; set; }
#endif
        /// <summary>Marks shipment as to be delivered on a Saturday.</summary>
        public bool? SaturdayDelivery { get; set; }
        /// <summary>UPS only. Adds custom serial number reference to UPS labels.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields? SerialNumber { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields SerialNumber { get; set; }
#endif
        /// <summary>Request standard or adult signature confirmation. You can alternatively request Certified Mail (USPS only) or Indirect signature (FedEx only) or Carrier Confirmation (Deutsche Post only).</summary>
        public global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra_signature_confirmation? SignatureConfirmation { get; set; }
        /// <summary>UPS only. Adds custom store number reference to UPS labels.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields? StoreNumber { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields StoreNumber { get; set; }
#endif
        /// <summary>UPS only. Adds custom transaction reference number to UPS labels.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields? TransactionReferenceNumber { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields TransactionReferenceNumber { get; set; }
#endif
        /// <summary>UPS only. Request USMCA (United States-Mexico-Canada Agreement) preferential tariff treatment. When enabled, it includes the USMCA eligibility declaration in customs documentation.Supported routes and value limits:- USA/Canada → Mexico: ≤ $1,000 USD- Canada/Mexico → USA: ≤ $2,500 USD  - USA/Mexico → Canada: ≤ $3,300 CADOnly for declaration-only shipments, full USMCA - FormType 04 (Certificate of Origin) is not supported.</summary>
        public bool? UsmcaEligible { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra"/> and sets the default values.
        /// </summary>
        public ShipmentExtra()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accounts_receivable_customer_account", n => { AccountsReceivableCustomerAccount = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>(global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields.CreateFromDiscriminatorValue); } },
                { "alcohol", n => { Alcohol = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.Alcohol>(global::Soenneker.Shippo.OpenApiClient.Models.Alcohol.CreateFromDiscriminatorValue); } },
                { "ancillary_endorsement", n => { AncillaryEndorsement = n.GetEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra_ancillary_endorsement>(); } },
                { "appropriation_number", n => { AppropriationNumber = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>(global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields.CreateFromDiscriminatorValue); } },
                { "authority_to_leave", n => { AuthorityToLeave = n.GetBoolValue(); } },
                { "bill_of_lading_number", n => { BillOfLadingNumber = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>(global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields.CreateFromDiscriminatorValue); } },
                { "billing", n => { Billing = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.Billing>(global::Soenneker.Shippo.OpenApiClient.Models.Billing.CreateFromDiscriminatorValue); } },
                { "bypass_address_validation", n => { BypassAddressValidation = n.GetBoolValue(); } },
                { "COD", n => { COD = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.COD>(global::Soenneker.Shippo.OpenApiClient.Models.COD.CreateFromDiscriminatorValue); } },
                { "carbon_neutral", n => { CarbonNeutral = n.GetBoolValue(); } },
                { "carrier_hub_id", n => { CarrierHubId = n.GetStringValue(); } },
                { "carrier_hub_travel_time", n => { CarrierHubTravelTime = n.GetIntValue(); } },
                { "cod_number", n => { CodNumber = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>(global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields.CreateFromDiscriminatorValue); } },
                { "container_type", n => { ContainerType = n.GetStringValue(); } },
                { "critical_pull_time", n => { CriticalPullTime = n.GetStringValue(); } },
                { "customer_branch", n => { CustomerBranch = n.GetStringValue(); } },
                { "customer_reference", n => { CustomerReference = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CustomerReference>(global::Soenneker.Shippo.OpenApiClient.Models.CustomerReference.CreateFromDiscriminatorValue); } },
                { "dangerous_goods", n => { DangerousGoods = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.DangerousGoodsObject>(global::Soenneker.Shippo.OpenApiClient.Models.DangerousGoodsObject.CreateFromDiscriminatorValue); } },
                { "dangerous_goods_code", n => { DangerousGoodsCode = n.GetEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra_dangerous_goods_code>(); } },
                { "dealer_order_number", n => { DealerOrderNumber = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>(global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields.CreateFromDiscriminatorValue); } },
                { "delivery_instructions", n => { DeliveryInstructions = n.GetStringValue(); } },
                { "dept_number", n => { DeptNumber = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.DepartmentNumber>(global::Soenneker.Shippo.OpenApiClient.Models.DepartmentNumber.CreateFromDiscriminatorValue); } },
                { "dry_ice", n => { DryIce = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.DryIce>(global::Soenneker.Shippo.OpenApiClient.Models.DryIce.CreateFromDiscriminatorValue); } },
                { "fda_product_code", n => { FdaProductCode = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>(global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields.CreateFromDiscriminatorValue); } },
                { "fulfillment_center", n => { FulfillmentCenter = n.GetStringValue(); } },
                { "insurance", n => { Insurance = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.Insurance>(global::Soenneker.Shippo.OpenApiClient.Models.Insurance.CreateFromDiscriminatorValue); } },
                { "invoice_number", n => { InvoiceNumber = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.InvoiceNumber>(global::Soenneker.Shippo.OpenApiClient.Models.InvoiceNumber.CreateFromDiscriminatorValue); } },
                { "is_return", n => { IsReturn = n.GetBoolValue(); } },
                { "lasership_attrs", n => { LasershipAttrs = n.GetCollectionOfEnumValues<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtraLasershipAttributesEnum>()?.AsList(); } },
                { "lasership_declared_value", n => { LasershipDeclaredValue = n.GetStringValue(); } },
                { "manifest_number", n => { ManifestNumber = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>(global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields.CreateFromDiscriminatorValue); } },
                { "model_number", n => { ModelNumber = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>(global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields.CreateFromDiscriminatorValue); } },
                { "part_number", n => { PartNumber = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>(global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields.CreateFromDiscriminatorValue); } },
                { "po_number", n => { PoNumber = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.PoNumber>(global::Soenneker.Shippo.OpenApiClient.Models.PoNumber.CreateFromDiscriminatorValue); } },
                { "preferred_delivery_timeframe", n => { PreferredDeliveryTimeframe = n.GetEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra_preferred_delivery_timeframe>(); } },
                { "premium", n => { Premium = n.GetBoolValue(); } },
                { "production_code", n => { ProductionCode = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>(global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields.CreateFromDiscriminatorValue); } },
                { "purchase_request_number", n => { PurchaseRequestNumber = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>(global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields.CreateFromDiscriminatorValue); } },
                { "qr_code_requested", n => { QrCodeRequested = n.GetBoolValue(); } },
                { "reference_1", n => { Reference1 = n.GetStringValue(); } },
                { "reference_2", n => { Reference2 = n.GetStringValue(); } },
                { "request_retail_rates", n => { RequestRetailRates = n.GetBoolValue(); } },
                { "return_service_type", n => { ReturnServiceType = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra.ShipmentExtra_return_service_type>(global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra.ShipmentExtra_return_service_type.CreateFromDiscriminatorValue); } },
                { "rma_number", n => { RmaNumber = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.RmaNumber>(global::Soenneker.Shippo.OpenApiClient.Models.RmaNumber.CreateFromDiscriminatorValue); } },
                { "salesperson_number", n => { SalespersonNumber = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>(global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields.CreateFromDiscriminatorValue); } },
                { "saturday_delivery", n => { SaturdayDelivery = n.GetBoolValue(); } },
                { "serial_number", n => { SerialNumber = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>(global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields.CreateFromDiscriminatorValue); } },
                { "signature_confirmation", n => { SignatureConfirmation = n.GetEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra_signature_confirmation>(); } },
                { "store_number", n => { StoreNumber = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>(global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields.CreateFromDiscriminatorValue); } },
                { "transaction_reference_number", n => { TransactionReferenceNumber = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>(global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields.CreateFromDiscriminatorValue); } },
                { "usmca_eligible", n => { UsmcaEligible = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>("accounts_receivable_customer_account", AccountsReceivableCustomerAccount);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.Alcohol>("alcohol", Alcohol);
            writer.WriteEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra_ancillary_endorsement>("ancillary_endorsement", AncillaryEndorsement);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>("appropriation_number", AppropriationNumber);
            writer.WriteBoolValue("authority_to_leave", AuthorityToLeave);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.Billing>("billing", Billing);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>("bill_of_lading_number", BillOfLadingNumber);
            writer.WriteBoolValue("bypass_address_validation", BypassAddressValidation);
            writer.WriteBoolValue("carbon_neutral", CarbonNeutral);
            writer.WriteStringValue("carrier_hub_id", CarrierHubId);
            writer.WriteIntValue("carrier_hub_travel_time", CarrierHubTravelTime);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.COD>("COD", COD);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>("cod_number", CodNumber);
            writer.WriteStringValue("container_type", ContainerType);
            writer.WriteStringValue("critical_pull_time", CriticalPullTime);
            writer.WriteStringValue("customer_branch", CustomerBranch);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CustomerReference>("customer_reference", CustomerReference);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.DangerousGoodsObject>("dangerous_goods", DangerousGoods);
            writer.WriteEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra_dangerous_goods_code>("dangerous_goods_code", DangerousGoodsCode);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>("dealer_order_number", DealerOrderNumber);
            writer.WriteStringValue("delivery_instructions", DeliveryInstructions);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.DepartmentNumber>("dept_number", DeptNumber);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.DryIce>("dry_ice", DryIce);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>("fda_product_code", FdaProductCode);
            writer.WriteStringValue("fulfillment_center", FulfillmentCenter);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.Insurance>("insurance", Insurance);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.InvoiceNumber>("invoice_number", InvoiceNumber);
            writer.WriteBoolValue("is_return", IsReturn);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtraLasershipAttributesEnum>("lasership_attrs", LasershipAttrs);
            writer.WriteStringValue("lasership_declared_value", LasershipDeclaredValue);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>("manifest_number", ManifestNumber);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>("model_number", ModelNumber);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>("part_number", PartNumber);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.PoNumber>("po_number", PoNumber);
            writer.WriteEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra_preferred_delivery_timeframe>("preferred_delivery_timeframe", PreferredDeliveryTimeframe);
            writer.WriteBoolValue("premium", Premium);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>("production_code", ProductionCode);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>("purchase_request_number", PurchaseRequestNumber);
            writer.WriteBoolValue("qr_code_requested", QrCodeRequested);
            writer.WriteStringValue("reference_1", Reference1);
            writer.WriteStringValue("reference_2", Reference2);
            writer.WriteBoolValue("request_retail_rates", RequestRetailRates);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra.ShipmentExtra_return_service_type>("return_service_type", ReturnServiceType);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.RmaNumber>("rma_number", RmaNumber);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>("salesperson_number", SalespersonNumber);
            writer.WriteBoolValue("saturday_delivery", SaturdayDelivery);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>("serial_number", SerialNumber);
            writer.WriteEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra_signature_confirmation>("signature_confirmation", SignatureConfirmation);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>("store_number", StoreNumber);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.UPSReferenceFields>("transaction_reference_number", TransactionReferenceNumber);
            writer.WriteBoolValue("usmca_eligible", UsmcaEligible);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtraReturnServiceTypeLasershipEnum"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtraReturnServiceTypeUPSEnum"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ShipmentExtra_return_service_type : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtraReturnServiceTypeLasershipEnum"/></summary>
            public global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtraReturnServiceTypeLasershipEnum? ShipmentExtraReturnServiceTypeLasershipEnum { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtraReturnServiceTypeUPSEnum"/></summary>
            public global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtraReturnServiceTypeUPSEnum? ShipmentExtraReturnServiceTypeUPSEnum { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra.ShipmentExtra_return_service_type"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra.ShipmentExtra_return_service_type CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra.ShipmentExtra_return_service_type();
                if(parseNode.GetEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtraReturnServiceTypeLasershipEnum>() is global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtraReturnServiceTypeLasershipEnum shipmentExtraReturnServiceTypeLasershipEnumValue)
                {
                    result.ShipmentExtraReturnServiceTypeLasershipEnum = shipmentExtraReturnServiceTypeLasershipEnumValue;
                }
                else if(parseNode.GetEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtraReturnServiceTypeUPSEnum>() is global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtraReturnServiceTypeUPSEnum shipmentExtraReturnServiceTypeUPSEnumValue)
                {
                    result.ShipmentExtraReturnServiceTypeUPSEnum = shipmentExtraReturnServiceTypeUPSEnumValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ShipmentExtraReturnServiceTypeLasershipEnum != null)
                {
                    writer.WriteEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtraReturnServiceTypeLasershipEnum>(null, ShipmentExtraReturnServiceTypeLasershipEnum);
                }
                else if(ShipmentExtraReturnServiceTypeUPSEnum != null)
                {
                    writer.WriteEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtraReturnServiceTypeUPSEnum>(null, ShipmentExtraReturnServiceTypeUPSEnum);
                }
            }
        }
    }
}
#pragma warning restore CS0618
