// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    /// <summary>`Waiting` shipments have been successfully submitted but not yet been processed. `Queued` shipments are currently being processed. `Success` shipments have been processed successfully, meaning that rate generation has concluded. `Error` does not occur currently and is reserved for future use.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ShipmentStatus
    {
        [EnumMember(Value = "ERROR")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "QUEUED")]
        #pragma warning disable CS1591
        Queued,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUCCESS")]
        #pragma warning disable CS1591
        Success,
        #pragma warning restore CS1591
        [EnumMember(Value = "WAITING")]
        #pragma warning disable CS1591
        Waiting,
        #pragma warning restore CS1591
    }
}
