// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationCreateRequest"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2CustomsDeclarationBranch2"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ShipmentCreateRequestAllOf2CustomsDeclaration : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationCreateRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationCreateRequest? CustomsDeclarationCreateRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationCreateRequest CustomsDeclarationCreateRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2CustomsDeclarationBranch2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2CustomsDeclarationBranch2? ShipmentCreateRequestAllOf2CustomsDeclarationBranch2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2CustomsDeclarationBranch2 ShipmentCreateRequestAllOf2CustomsDeclarationBranch2 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2CustomsDeclaration"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2CustomsDeclaration CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2CustomsDeclaration();
            if("CustomsDeclarationCreateRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CustomsDeclarationCreateRequest = new global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationCreateRequest();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CustomsDeclarationCreateRequest != null)
            {
                return CustomsDeclarationCreateRequest.GetFieldDeserializers();
            }
            else if(ShipmentCreateRequestAllOf2CustomsDeclarationBranch2 != null)
            {
                return ShipmentCreateRequestAllOf2CustomsDeclarationBranch2.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(CustomsDeclarationCreateRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CustomsDeclarationCreateRequest>(null, CustomsDeclarationCreateRequest);
            }
            else if(ShipmentCreateRequestAllOf2CustomsDeclarationBranch2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2CustomsDeclarationBranch2>(null, ShipmentCreateRequestAllOf2CustomsDeclarationBranch2);
            }
        }
    }
}
#pragma warning restore CS0618
