// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    /// <summary>Specify an ancillary service endorsement to provide the USPS with instructions on how to handle undeliverable-as-addressed pieces (DHL eCommerce only).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ShipmentExtra_ancillary_endorsement
    {
        [EnumMember(Value = "FORWARDING_SERVICE_REQUESTED")]
        #pragma warning disable CS1591
        FORWARDING_SERVICE_REQUESTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "RETURN_SERVICE_REQUESTED")]
        #pragma warning disable CS1591
        RETURN_SERVICE_REQUESTED,
        #pragma warning restore CS1591
    }
}
