// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ShipmentExtraReturnServiceTypeUPSEnum
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "PRINT_AND_MAIL")]
        #pragma warning disable CS1591
        PRINT_AND_MAIL,
        #pragma warning restore CS1591
        [EnumMember(Value = "ATTEMPT_1")]
        #pragma warning disable CS1591
        ATTEMPT_1,
        #pragma warning restore CS1591
        [EnumMember(Value = "ATTEMPT_3")]
        #pragma warning disable CS1591
        ATTEMPT_3,
        #pragma warning restore CS1591
        [EnumMember(Value = "ELECTRONIC_LABEL")]
        #pragma warning disable CS1591
        ELECTRONIC_LABEL,
        #pragma warning restore CS1591
    }
}
