// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ShipmentCreateRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The address_from property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2AddressFrom? AddressFrom { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2AddressFrom AddressFrom { get; set; }
#endif
        /// <summary>The address_return property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2AddressReturn? AddressReturn { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2AddressReturn AddressReturn { get; set; }
#endif
        /// <summary>The address_to property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2AddressTo? AddressTo { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2AddressTo AddressTo { get; set; }
#endif
        /// <summary>The async property</summary>
        public bool? Async { get; set; }
        /// <summary>List of &lt;a href=&quot;/shippoapi/public-api/carrier-accounts&quot;&gt;Carrier Accounts&lt;/a&gt; `object_id`s used to filter the returned rates.  If set, only rates from these carriers will be returned.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CarrierAccounts { get; set; }
#nullable restore
#else
        public List<string> CarrierAccounts { get; set; }
#endif
        /// <summary>The customs_declaration property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2CustomsDeclaration? CustomsDeclaration { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2CustomsDeclaration CustomsDeclaration { get; set; }
#endif
        /// <summary>An object holding optional extra services to be requested.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra? Extra { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra Extra { get; set; }
#endif
        /// <summary>A string of up to 100 characters that can be filled with any additional information you want to attach to the object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Metadata { get; set; }
#nullable restore
#else
        public string Metadata { get; set; }
#endif
        /// <summary>List of parcels to be shipped.**Carrier-Specific Constraints:**| Carrier | Constraints ||:---|:---|| FedEx | Max 30 items |</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2ParcelsItem>? Parcels { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2ParcelsItem> Parcels { get; set; }
#endif
        /// <summary>Date the shipment will be tendered to the carrier. Must be in the format `2014-01-18T00:35:03.463Z`. Defaults to current date and time if no value is provided. Please note that some carriers require this value tobe in the future, on a working day, or similar.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShipmentDate { get; set; }
#nullable restore
#else
        public string ShipmentDate { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequest"/> and sets the default values.
        /// </summary>
        public ShipmentCreateRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address_from", n => { AddressFrom = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2AddressFrom>(global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2AddressFrom.CreateFromDiscriminatorValue); } },
                { "address_return", n => { AddressReturn = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2AddressReturn>(global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2AddressReturn.CreateFromDiscriminatorValue); } },
                { "address_to", n => { AddressTo = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2AddressTo>(global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2AddressTo.CreateFromDiscriminatorValue); } },
                { "async", n => { Async = n.GetBoolValue(); } },
                { "carrier_accounts", n => { CarrierAccounts = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "customs_declaration", n => { CustomsDeclaration = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2CustomsDeclaration>(global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2CustomsDeclaration.CreateFromDiscriminatorValue); } },
                { "extra", n => { Extra = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra>(global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra.CreateFromDiscriminatorValue); } },
                { "metadata", n => { Metadata = n.GetStringValue(); } },
                { "parcels", n => { Parcels = n.GetCollectionOfObjectValues<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2ParcelsItem>(global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2ParcelsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "shipment_date", n => { ShipmentDate = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2AddressFrom>("address_from", AddressFrom);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2AddressReturn>("address_return", AddressReturn);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2AddressTo>("address_to", AddressTo);
            writer.WriteBoolValue("async", Async);
            writer.WriteCollectionOfPrimitiveValues<string>("carrier_accounts", CarrierAccounts);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2CustomsDeclaration>("customs_declaration", CustomsDeclaration);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentExtra>("extra", Extra);
            writer.WriteStringValue("metadata", Metadata);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Shippo.OpenApiClient.Models.ShipmentCreateRequestAllOf2ParcelsItem>("parcels", Parcels);
            writer.WriteStringValue("shipment_date", ShipmentDate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
