// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    /// <summary>
    /// The latest tracking information of this shipment.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TrackingStatus : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An object containing zip, city, state and country information of the tracking event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.TrackingStatusLocation? Location { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.TrackingStatusLocation Location { get; set; }
#endif
        /// <summary>The object_created property</summary>
        public DateTimeOffset? ObjectCreated { get; set; }
        /// <summary>The object_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObjectId { get; set; }
#nullable restore
#else
        public string ObjectId { get; set; }
#endif
        /// <summary>The object_updated property</summary>
        public DateTimeOffset? ObjectUpdated { get; set; }
        /// <summary>Indicates the high level status of the shipment.</summary>
        public global::Soenneker.Shippo.OpenApiClient.Models.TrackingStatusEnum? Status { get; set; }
        /// <summary>Date and time when the carrier scanned this tracking event. This is displayed in UTC.</summary>
        public DateTimeOffset? StatusDate { get; set; }
        /// <summary>The human-readable description of the status.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusDetails { get; set; }
#nullable restore
#else
        public string StatusDetails { get; set; }
#endif
        /// <summary>A finer-grained classification of the tracking event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.TrackingStatusSubstatus? Substatus { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.TrackingStatusSubstatus Substatus { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Shippo.OpenApiClient.Models.TrackingStatus"/> and sets the default values.
        /// </summary>
        public TrackingStatus()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.TrackingStatus"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Shippo.OpenApiClient.Models.TrackingStatus CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Shippo.OpenApiClient.Models.TrackingStatus();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "location", n => { Location = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.TrackingStatusLocation>(global::Soenneker.Shippo.OpenApiClient.Models.TrackingStatusLocation.CreateFromDiscriminatorValue); } },
                { "object_created", n => { ObjectCreated = n.GetDateTimeOffsetValue(); } },
                { "object_id", n => { ObjectId = n.GetStringValue(); } },
                { "object_updated", n => { ObjectUpdated = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.TrackingStatusEnum>(); } },
                { "status_date", n => { StatusDate = n.GetDateTimeOffsetValue(); } },
                { "status_details", n => { StatusDetails = n.GetStringValue(); } },
                { "substatus", n => { Substatus = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.TrackingStatusSubstatus>(global::Soenneker.Shippo.OpenApiClient.Models.TrackingStatusSubstatus.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.TrackingStatusLocation>("location", Location);
            writer.WriteDateTimeOffsetValue("object_created", ObjectCreated);
            writer.WriteStringValue("object_id", ObjectId);
            writer.WriteDateTimeOffsetValue("object_updated", ObjectUpdated);
            writer.WriteEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.TrackingStatusEnum>("status", Status);
            writer.WriteDateTimeOffsetValue("status_date", StatusDate);
            writer.WriteStringValue("status_details", StatusDetails);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.TrackingStatusSubstatus>("substatus", Substatus);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
