// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    /// <summary>Indicates the high level status of the shipment.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TrackingStatusEnum
    {
        [EnumMember(Value = "UNKNOWN")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRE_TRANSIT")]
        #pragma warning disable CS1591
        PreTransit,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRANSIT")]
        #pragma warning disable CS1591
        Transit,
        #pragma warning restore CS1591
        [EnumMember(Value = "DELIVERED")]
        #pragma warning disable CS1591
        Delivered,
        #pragma warning restore CS1591
        [EnumMember(Value = "RETURNED")]
        #pragma warning disable CS1591
        Returned,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAILURE")]
        #pragma warning disable CS1591
        Failure,
        #pragma warning restore CS1591
    }
}
