// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Transaction : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A URL pointing to the commercial invoice as a 8.5x11 inch PDF file. A value will only be returned if the Transactions has been processed successfully and if the shipment is international.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CommercialInvoiceUrl { get; set; }
#nullable restore
#else
        public string CommercialInvoiceUrl { get; set; }
#endif
        /// <summary>The created_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.Transaction.Transaction_created_by? CreatedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.Transaction.Transaction_created_by CreatedBy { get; set; }
#endif
        /// <summary>The estimated time of arrival according to the carrier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Eta { get; set; }
#nullable restore
#else
        public string Eta { get; set; }
#endif
        /// <summary>Print format of the &lt;a href=&quot;https://docs.goshippo.com/docs/shipments/shippinglabelsizes/&quot;&gt;label&lt;/a&gt;. If empty, will use the default format set from &lt;a href=&quot;https://apps.goshippo.com/settings/labels&quot;&gt;the Shippo dashboard.&lt;/a&gt;</summary>
        public global::Soenneker.Shippo.OpenApiClient.Models.LabelFileTypeEnum? LabelFileType { get; set; }
        /// <summary>A URL pointing directly to the label in the format you&apos;ve set in your settings. A value will only be returned if the Transactions has been processed successfully.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LabelUrl { get; set; }
#nullable restore
#else
        public string LabelUrl { get; set; }
#endif
        /// <summary>The messages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Shippo.OpenApiClient.Models.ResponseMessage>? Messages { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Shippo.OpenApiClient.Models.ResponseMessage> Messages { get; set; }
#endif
        /// <summary>A string of up to 100 characters that can be filled with any additional information you want to attach to the object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Metadata { get; set; }
#nullable restore
#else
        public string Metadata { get; set; }
#endif
        /// <summary>Date and time of Transaction creation.</summary>
        public DateTimeOffset? ObjectCreated { get; set; }
        /// <summary>Unique identifier of the given Transaction object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObjectId { get; set; }
#nullable restore
#else
        public string ObjectId { get; set; }
#endif
        /// <summary>Username of the user who created the Transaction object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObjectOwner { get; set; }
#nullable restore
#else
        public string ObjectOwner { get; set; }
#endif
        /// <summary>Indicates the validity of the enclosing object</summary>
        public global::Soenneker.Shippo.OpenApiClient.Models.ObjectStateEnum? ObjectState { get; set; }
        /// <summary>Date and time of last Transaction update.</summary>
        public DateTimeOffset? ObjectUpdated { get; set; }
        /// <summary>Object ID of the Parcel object that is being shipped.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Parcel { get; set; }
#nullable restore
#else
        public string Parcel { get; set; }
#endif
        /// <summary>A URL pointing directly to the QR code in PNG format. A value will only be returned if requested using qr_code_requested flag and the carrier provides such an option.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? QrCodeUrl { get; set; }
#nullable restore
#else
        public string QrCodeUrl { get; set; }
#endif
        /// <summary>ID of the Rate object for which a Label has to be obtained.  If you purchase a label by calling the transaction endpoint without a rate (instalabel), this field will be a simplified Rate object in the Transaction model returned from the POST request.&lt;/br&gt;Note, only rates less than 7 days old can be purchased to ensure up-to-date pricing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.Transaction.Transaction_rate? Rate { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.Transaction.Transaction_rate Rate { get; set; }
#endif
        /// <summary>Indicates the status of the Transaction.</summary>
        public global::Soenneker.Shippo.OpenApiClient.Models.TransactionStatusEnum? Status { get; set; }
        /// <summary>Indicates whether the object has been created in test mode.</summary>
        public bool? Test { get; set; }
        /// <summary>The carrier-specific tracking number that can be used to track the Shipment. A value will only be returned if the Rate is for a trackable Shipment and if the Transactions has been processed successfully.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TrackingNumber { get; set; }
#nullable restore
#else
        public string TrackingNumber { get; set; }
#endif
        /// <summary>Indicates the high level status of the shipment.</summary>
        public global::Soenneker.Shippo.OpenApiClient.Models.TrackingStatusEnum? TrackingStatus { get; set; }
        /// <summary>A link to track this item on the carrier-provided tracking website. A value will only be returned if tracking is available and the carrier provides such a service.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TrackingUrlProvider { get; set; }
#nullable restore
#else
        public string TrackingUrlProvider { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Shippo.OpenApiClient.Models.Transaction"/> and sets the default values.
        /// </summary>
        public Transaction()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.Transaction"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Shippo.OpenApiClient.Models.Transaction CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Shippo.OpenApiClient.Models.Transaction();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "commercial_invoice_url", n => { CommercialInvoiceUrl = n.GetStringValue(); } },
                { "created_by", n => { CreatedBy = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.Transaction.Transaction_created_by>(global::Soenneker.Shippo.OpenApiClient.Models.Transaction.Transaction_created_by.CreateFromDiscriminatorValue); } },
                { "eta", n => { Eta = n.GetStringValue(); } },
                { "label_file_type", n => { LabelFileType = n.GetEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.LabelFileTypeEnum>(); } },
                { "label_url", n => { LabelUrl = n.GetStringValue(); } },
                { "messages", n => { Messages = n.GetCollectionOfObjectValues<global::Soenneker.Shippo.OpenApiClient.Models.ResponseMessage>(global::Soenneker.Shippo.OpenApiClient.Models.ResponseMessage.CreateFromDiscriminatorValue)?.AsList(); } },
                { "metadata", n => { Metadata = n.GetStringValue(); } },
                { "object_created", n => { ObjectCreated = n.GetDateTimeOffsetValue(); } },
                { "object_id", n => { ObjectId = n.GetStringValue(); } },
                { "object_owner", n => { ObjectOwner = n.GetStringValue(); } },
                { "object_state", n => { ObjectState = n.GetEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.ObjectStateEnum>(); } },
                { "object_updated", n => { ObjectUpdated = n.GetDateTimeOffsetValue(); } },
                { "parcel", n => { Parcel = n.GetStringValue(); } },
                { "qr_code_url", n => { QrCodeUrl = n.GetStringValue(); } },
                { "rate", n => { Rate = n.GetObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.Transaction.Transaction_rate>(global::Soenneker.Shippo.OpenApiClient.Models.Transaction.Transaction_rate.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.TransactionStatusEnum>(); } },
                { "test", n => { Test = n.GetBoolValue(); } },
                { "tracking_number", n => { TrackingNumber = n.GetStringValue(); } },
                { "tracking_status", n => { TrackingStatus = n.GetEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.TrackingStatusEnum>(); } },
                { "tracking_url_provider", n => { TrackingUrlProvider = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("commercial_invoice_url", CommercialInvoiceUrl);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.Transaction.Transaction_created_by>("created_by", CreatedBy);
            writer.WriteStringValue("eta", Eta);
            writer.WriteEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.LabelFileTypeEnum>("label_file_type", LabelFileType);
            writer.WriteStringValue("label_url", LabelUrl);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Shippo.OpenApiClient.Models.ResponseMessage>("messages", Messages);
            writer.WriteStringValue("metadata", Metadata);
            writer.WriteDateTimeOffsetValue("object_created", ObjectCreated);
            writer.WriteStringValue("object_id", ObjectId);
            writer.WriteStringValue("object_owner", ObjectOwner);
            writer.WriteEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.ObjectStateEnum>("object_state", ObjectState);
            writer.WriteDateTimeOffsetValue("object_updated", ObjectUpdated);
            writer.WriteStringValue("parcel", Parcel);
            writer.WriteStringValue("qr_code_url", QrCodeUrl);
            writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.Transaction.Transaction_rate>("rate", Rate);
            writer.WriteEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.TransactionStatusEnum>("status", Status);
            writer.WriteBoolValue("test", Test);
            writer.WriteStringValue("tracking_number", TrackingNumber);
            writer.WriteEnumValue<global::Soenneker.Shippo.OpenApiClient.Models.TrackingStatusEnum>("tracking_status", TrackingStatus);
            writer.WriteStringValue("tracking_url_provider", TrackingUrlProvider);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Shippo.OpenApiClient.Models.Transaction_created_byMember1"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.Transaction_created_byMember2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Transaction_created_by : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.Transaction_created_byMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Shippo.OpenApiClient.Models.Transaction_created_byMember1? TransactionCreatedByMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Shippo.OpenApiClient.Models.Transaction_created_byMember1 TransactionCreatedByMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.Transaction_created_byMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Shippo.OpenApiClient.Models.Transaction_created_byMember2? TransactionCreatedByMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.Shippo.OpenApiClient.Models.Transaction_created_byMember2 TransactionCreatedByMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.Transaction.Transaction_created_by"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Shippo.OpenApiClient.Models.Transaction.Transaction_created_by CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Shippo.OpenApiClient.Models.Transaction.Transaction_created_by();
                result.TransactionCreatedByMember1 = new global::Soenneker.Shippo.OpenApiClient.Models.Transaction_created_byMember1();
                result.TransactionCreatedByMember2 = new global::Soenneker.Shippo.OpenApiClient.Models.Transaction_created_byMember2();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(TransactionCreatedByMember1 != null || TransactionCreatedByMember2 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(TransactionCreatedByMember1, TransactionCreatedByMember2);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.Transaction_created_byMember1>(null, TransactionCreatedByMember1, TransactionCreatedByMember2);
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CoreRate"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Transaction_rate : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CoreRate"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Shippo.OpenApiClient.Models.CoreRate? CoreRate { get; set; }
#nullable restore
#else
            public global::Soenneker.Shippo.OpenApiClient.Models.CoreRate CoreRate { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.Transaction.Transaction_rate"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Shippo.OpenApiClient.Models.Transaction.Transaction_rate CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Shippo.OpenApiClient.Models.Transaction.Transaction_rate();
                if("CoreRate".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CoreRate = new global::Soenneker.Shippo.OpenApiClient.Models.CoreRate();
                }
                else if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CoreRate != null)
                {
                    return CoreRate.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CoreRate != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CoreRate>(null, CoreRate);
                }
                else if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
            }
        }
    }
}
#pragma warning restore CS0618
