// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CoreRate"/>, <see cref="global::Soenneker.Shippo.OpenApiClient.Models.TransactionRateBranch2"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransactionRate : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.CoreRate"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.CoreRate? CoreRate { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.CoreRate CoreRate { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Shippo.OpenApiClient.Models.TransactionRateBranch2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Shippo.OpenApiClient.Models.TransactionRateBranch2? TransactionRateBranch2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Shippo.OpenApiClient.Models.TransactionRateBranch2 TransactionRateBranch2 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.TransactionRate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Shippo.OpenApiClient.Models.TransactionRate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Shippo.OpenApiClient.Models.TransactionRate();
            if("CoreRate".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CoreRate = new global::Soenneker.Shippo.OpenApiClient.Models.CoreRate();
            }
            else if("TransactionRate_2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.TransactionRateBranch2 = new global::Soenneker.Shippo.OpenApiClient.Models.TransactionRateBranch2();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CoreRate != null)
            {
                return CoreRate.GetFieldDeserializers();
            }
            else if(TransactionRateBranch2 != null)
            {
                return TransactionRateBranch2.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(CoreRate != null)
            {
                writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.CoreRate>(null, CoreRate);
            }
            else if(TransactionRateBranch2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Shippo.OpenApiClient.Models.TransactionRateBranch2>(null, TransactionRateBranch2);
            }
        }
    }
}
#pragma warning restore CS0618
