// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    /// <summary>
    /// An array of additional parameters for the account, such as e.g. password or token.Please check the &lt;a href=&quot;https://docs.goshippo.com/docs/carriers/carrieraccounts/&quot;&gt;carrier accounts tutorial&lt;/a&gt; page for the parameters per carrier.&lt;br&gt; To protect account information, this field will be masked in any API response.In the case of masked fields, they should be handled carefully.Fields also must consider: - Not providing a *fields* in parameters will not result in a change to any configured value - Providing a value in a *masked field* with ****** (exactly 6 asterisks) will not change the configured value - Providing *field* with null will clear the configured value - Providing *field* with any other value will change the configured value and may affect the behavior of the account.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UPSConnectExistingOwnAccountParameters : IAdditionalDataHolder, IParsable
    {
        /// <summary>The UPS account number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountNumber { get; set; }
#nullable restore
#else
        public string AccountNumber { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Only required if has_invoice is true. Country associated with the account that issued the invoice</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AiaCountryIso2 { get; set; }
#nullable restore
#else
        public string AiaCountryIso2 { get; set; }
#endif
        /// <summary>The billing_address_city property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BillingAddressCity { get; set; }
#nullable restore
#else
        public string BillingAddressCity { get; set; }
#endif
        /// <summary>The billing_address_country_iso2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BillingAddressCountryIso2 { get; set; }
#nullable restore
#else
        public string BillingAddressCountryIso2 { get; set; }
#endif
        /// <summary>The billing_address_state property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BillingAddressState { get; set; }
#nullable restore
#else
        public string BillingAddressState { get; set; }
#endif
        /// <summary>The billing_address_street1 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BillingAddressStreet1 { get; set; }
#nullable restore
#else
        public string BillingAddressStreet1 { get; set; }
#endif
        /// <summary>Empty string acceptable for billing_address_street2</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BillingAddressStreet2 { get; set; }
#nullable restore
#else
        public string BillingAddressStreet2 { get; set; }
#endif
        /// <summary>The billing_address_zip property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BillingAddressZip { get; set; }
#nullable restore
#else
        public string BillingAddressZip { get; set; }
#endif
        /// <summary>The collec_country_iso2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CollecCountryIso2 { get; set; }
#nullable restore
#else
        public string CollecCountryIso2 { get; set; }
#endif
        /// <summary>Zip code of the collection/pickup address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CollecZip { get; set; }
#nullable restore
#else
        public string CollecZip { get; set; }
#endif
        /// <summary>Company name. Full name is acceptable in this field if the user has no company name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Company { get; set; }
#nullable restore
#else
        public string Company { get; set; }
#endif
        /// <summary>Only required if has_invoice is true. 3-letter currency code associated with invoice_value</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrencyCode { get; set; }
#nullable restore
#else
        public string CurrencyCode { get; set; }
#endif
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The full_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FullName { get; set; }
#nullable restore
#else
        public string FullName { get; set; }
#endif
        /// <summary>true if user has been issued a UPS invoice within the past 90 days for the US or Canada; and 45 days for any other countries. User can use data from any of the last 3 invoices</summary>
        public bool? HasInvoice { get; set; }
        /// <summary>Only required if aia_country_iso2 is US and has_invoice is true.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvoiceControlid { get; set; }
#nullable restore
#else
        public string InvoiceControlid { get; set; }
#endif
        /// <summary>Only required if has_invoice is true. Date the invoice was issued. yyyymmdd format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvoiceDate { get; set; }
#nullable restore
#else
        public string InvoiceDate { get; set; }
#endif
        /// <summary>The invoice_number property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvoiceNumber { get; set; }
#nullable restore
#else
        public string InvoiceNumber { get; set; }
#endif
        /// <summary>Only required if has_invoice is true. Max 16 digits before decimal and 2 digits after decimal</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvoiceValue { get; set; }
#nullable restore
#else
        public string InvoiceValue { get; set; }
#endif
        /// <summary>The phone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Phone { get; set; }
#nullable restore
#else
        public string Phone { get; set; }
#endif
        /// <summary>User&apos;s title, e.g. including but not limited to Manager, Doctor, Artist, Engineer, Mr, Ms, Mrs, Mx</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>Whether the user agrees to the UPS terms and conditions or not. Error 400 will be returned if passed in as false</summary>
        public bool? UpsAgreements { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Shippo.OpenApiClient.Models.UPSConnectExistingOwnAccountParameters"/> and sets the default values.
        /// </summary>
        public UPSConnectExistingOwnAccountParameters()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.UPSConnectExistingOwnAccountParameters"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Shippo.OpenApiClient.Models.UPSConnectExistingOwnAccountParameters CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Shippo.OpenApiClient.Models.UPSConnectExistingOwnAccountParameters();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_number", n => { AccountNumber = n.GetStringValue(); } },
                { "aia_country_iso2", n => { AiaCountryIso2 = n.GetStringValue(); } },
                { "billing_address_city", n => { BillingAddressCity = n.GetStringValue(); } },
                { "billing_address_country_iso2", n => { BillingAddressCountryIso2 = n.GetStringValue(); } },
                { "billing_address_state", n => { BillingAddressState = n.GetStringValue(); } },
                { "billing_address_street1", n => { BillingAddressStreet1 = n.GetStringValue(); } },
                { "billing_address_street2", n => { BillingAddressStreet2 = n.GetStringValue(); } },
                { "billing_address_zip", n => { BillingAddressZip = n.GetStringValue(); } },
                { "collec_country_iso2", n => { CollecCountryIso2 = n.GetStringValue(); } },
                { "collec_zip", n => { CollecZip = n.GetStringValue(); } },
                { "company", n => { Company = n.GetStringValue(); } },
                { "currency_code", n => { CurrencyCode = n.GetStringValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "full_name", n => { FullName = n.GetStringValue(); } },
                { "has_invoice", n => { HasInvoice = n.GetBoolValue(); } },
                { "invoice_controlid", n => { InvoiceControlid = n.GetStringValue(); } },
                { "invoice_date", n => { InvoiceDate = n.GetStringValue(); } },
                { "invoice_number", n => { InvoiceNumber = n.GetStringValue(); } },
                { "invoice_value", n => { InvoiceValue = n.GetStringValue(); } },
                { "phone", n => { Phone = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "ups_agreements", n => { UpsAgreements = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("account_number", AccountNumber);
            writer.WriteStringValue("aia_country_iso2", AiaCountryIso2);
            writer.WriteStringValue("billing_address_city", BillingAddressCity);
            writer.WriteStringValue("billing_address_country_iso2", BillingAddressCountryIso2);
            writer.WriteStringValue("billing_address_state", BillingAddressState);
            writer.WriteStringValue("billing_address_street1", BillingAddressStreet1);
            writer.WriteStringValue("billing_address_street2", BillingAddressStreet2);
            writer.WriteStringValue("billing_address_zip", BillingAddressZip);
            writer.WriteStringValue("collec_country_iso2", CollecCountryIso2);
            writer.WriteStringValue("collec_zip", CollecZip);
            writer.WriteStringValue("company", Company);
            writer.WriteStringValue("currency_code", CurrencyCode);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("full_name", FullName);
            writer.WriteBoolValue("has_invoice", HasInvoice);
            writer.WriteStringValue("invoice_controlid", InvoiceControlid);
            writer.WriteStringValue("invoice_date", InvoiceDate);
            writer.WriteStringValue("invoice_number", InvoiceNumber);
            writer.WriteStringValue("invoice_value", InvoiceValue);
            writer.WriteStringValue("phone", Phone);
            writer.WriteStringValue("title", Title);
            writer.WriteBoolValue("ups_agreements", UpsAgreements);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
