// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Shippo.OpenApiClient.Models
{
    /// <summary>The unit used for weight.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WeightUnitEnum
    {
        [EnumMember(Value = "g")]
        #pragma warning disable CS1591
        G,
        #pragma warning restore CS1591
        [EnumMember(Value = "kg")]
        #pragma warning disable CS1591
        Kg,
        #pragma warning restore CS1591
        [EnumMember(Value = "lb")]
        #pragma warning disable CS1591
        Lb,
        #pragma warning restore CS1591
        [EnumMember(Value = "oz")]
        #pragma warning disable CS1591
        Oz,
        #pragma warning restore CS1591
    }
}
