// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Shippo.OpenApiClient.Models;
using Soenneker.Shippo.OpenApiClient.Orders.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Shippo.OpenApiClient.Orders
{
    /// <summary>
    /// Builds and executes requests for operations under \orders
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OrdersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Shippo.OpenApiClient.orders.item collection</summary>
        /// <param name="position">Object ID of the order</param>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Orders.Item.WithOrderItemRequestBuilder"/></returns>
        public global::Soenneker.Shippo.OpenApiClient.Orders.Item.WithOrderItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("OrderId", position);
                return new global::Soenneker.Shippo.OpenApiClient.Orders.Item.WithOrderItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Shippo.OpenApiClient.Orders.OrdersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrdersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/orders{?end_date*,order_status%5B%5D*,page*,results*,shop_app*,start_date*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Shippo.OpenApiClient.Orders.OrdersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrdersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/orders{?end_date*,order_status%5B%5D*,page*,results*,shop_app*,start_date*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a list of all order objects.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.OrderPaginatedList"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Shippo.OpenApiClient.Models.BadRequest">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Shippo.OpenApiClient.Models.OrderPaginatedList?> GetAsync(Action<RequestConfiguration<global::Soenneker.Shippo.OpenApiClient.Orders.OrdersRequestBuilder.OrdersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Shippo.OpenApiClient.Models.OrderPaginatedList> GetAsync(Action<RequestConfiguration<global::Soenneker.Shippo.OpenApiClient.Orders.OrdersRequestBuilder.OrdersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Shippo.OpenApiClient.Models.BadRequest.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Shippo.OpenApiClient.Models.OrderPaginatedList>(requestInfo, global::Soenneker.Shippo.OpenApiClient.Models.OrderPaginatedList.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new order object.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Models.Order"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Shippo.OpenApiClient.Models.BadRequest">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Shippo.OpenApiClient.Models.Order?> PostAsync(global::Soenneker.Shippo.OpenApiClient.Models.OrderCreateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Shippo.OpenApiClient.Models.Order> PostAsync(global::Soenneker.Shippo.OpenApiClient.Models.OrderCreateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Shippo.OpenApiClient.Models.BadRequest.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Shippo.OpenApiClient.Models.Order>(requestInfo, global::Soenneker.Shippo.OpenApiClient.Models.Order.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a list of all order objects.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Shippo.OpenApiClient.Orders.OrdersRequestBuilder.OrdersRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Shippo.OpenApiClient.Orders.OrdersRequestBuilder.OrdersRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a new order object.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Shippo.OpenApiClient.Models.OrderCreateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Shippo.OpenApiClient.Models.OrderCreateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Shippo.OpenApiClient.Orders.OrdersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Shippo.OpenApiClient.Orders.OrdersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Shippo.OpenApiClient.Orders.OrdersRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a list of all order objects.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OrdersRequestBuilderGetQueryParameters 
        {
            /// <summary>Filter orders created before the input date and time (ISO 8601 UTC format).  This is based on the `placed_at` field, meaning when the order has been placed, not when the order object was created.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("end_date")]
            public string? EndDate { get; set; }
#nullable restore
#else
            [QueryParameter("end_date")]
            public string EndDate { get; set; }
#endif
            /// <summary>Filter orders by order status</summary>
            [Obsolete("This property is deprecated, use OrderStatusAsOrderStatusEnum instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("order_status%5B%5D")]
            public string[]? OrderStatus { get; set; }
#nullable restore
#else
            [QueryParameter("order_status%5B%5D")]
            public string[] OrderStatus { get; set; }
#endif
            /// <summary>Filter orders by order status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("order_status%5B%5D")]
            public global::Soenneker.Shippo.OpenApiClient.Models.OrderStatusEnum[]? OrderStatusAsOrderStatusEnum { get; set; }
#nullable restore
#else
            [QueryParameter("order_status%5B%5D")]
            public global::Soenneker.Shippo.OpenApiClient.Models.OrderStatusEnum[] OrderStatusAsOrderStatusEnum { get; set; }
#endif
            /// <summary>The page number you want to select</summary>
            [QueryParameter("page")]
            public long? Page { get; set; }
            /// <summary>The number of results to return per page (max 100)</summary>
            [QueryParameter("results")]
            public long? Results { get; set; }
            /// <summary>Filter orders by shop app</summary>
            [Obsolete("This property is deprecated, use ShopAppAsOrderShopAppEnum instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("shop_app")]
            public string? ShopApp { get; set; }
#nullable restore
#else
            [QueryParameter("shop_app")]
            public string ShopApp { get; set; }
#endif
            /// <summary>Filter orders by shop app</summary>
            [QueryParameter("shop_app")]
            public global::Soenneker.Shippo.OpenApiClient.Models.OrderShopAppEnum? ShopAppAsOrderShopAppEnum { get; set; }
            /// <summary>Filter orders created after the input date and time (ISO 8601 UTC format).  This is based on the `placed_at` field, meaning when the order has been placed, not when the order object was created.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("start_date")]
            public string? StartDate { get; set; }
#nullable restore
#else
            [QueryParameter("start_date")]
            public string StartDate { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OrdersRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.Shippo.OpenApiClient.Orders.OrdersRequestBuilder.OrdersRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OrdersRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
